In [ ]:
# Install necessary libraries if not already installed
!pip install requests beautifulsoup4 pandas

import requests
from bs4 import BeautifulSoup
import pandas as pd

def scrape_cafef_articles(url):
    """
    Scrapes article titles and publication times from a specified CafeF URL.

    Args:
        url (str): The URL of the CafeF page to scrape.

    Returns:
        pd.DataFrame: A DataFrame containing 'Title' and 'Time' of the articles.
    """
    try:
        # Send a GET request to the URL
        response = requests.get(url)
        # Check if the request was successful
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        print(f"Error accessing the URL: {e}")
        return pd.DataFrame() # Return an empty DataFrame on error

    # Parse the content of the page with BeautifulSoup
    soup = BeautifulSoup(response.content, 'html.parser')

    # Find the main container for the articles
    events_container = soup.find(id='divEvents')
    if not events_container:
        print("Could not find the 'divEvents' container.")
        return pd.DataFrame()

    # Find all list items (li) within the container, each representing an article
    articles = events_container.find_all('li')

    # Lists to store the scraped data
    titles = []
    times = []

    # Loop through each article item and extract the title and time
    for article in articles:
        # Extract the title from the 'a' tag
        title_tag = article.find('a')
        if title_tag:
            titles.append(title_tag.get_text(strip=True))
        else:
            titles.append(None) # Append None if title is not found

        # Extract the publication time from the 'span' tag
        time_tag = article.find('span')
        if time_tag:
            times.append(time_tag.get_text(strip=True))
        else:
            times.append(None) # Append None if time is not found

    # Create a pandas DataFrame from the collected data
    df = pd.DataFrame({
        'Title': titles,
        'Time': times
    })

    return df

# URL to scrape
url = "https://cafef.vn/du-lieu/tin-doanh-nghiep/vic/event.chn"

# Run the function and get the DataFrame
articles_df = scrape_cafef_articles(url)

# Display the DataFrame
if not articles_df.empty:
    print(articles_df.to_string())
else:
    print("DataFrame is empty. No data was scraped.")

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2025.8.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
                                                                                                                                                Title              Time
0                                               Vingroup và tỷ phú Phạm Nhật Vượng vừa lập “cú đúp” chưa từng có trong lịch sử thương trường Việt Nam  18/09/2025 11:22
1                             Từ ngày tỷ phú Phạm Nhật Vượng khuyên "chọn VIC thay vì vàng": Cổ phiếu VIC đã tăng gần 3 lần, còn vàng gần như đứng im  18/09/2025 07:33
2                                                                                              Vingroup đạt được cột mốc chưa từng có trong gần 5 năm  17/09/2025 15:57
3                                                       Vingroup của tỷ phú Phạm Nhật Vượng vượt qua Vietcombank, trở lại vị trí số 1 sàn chứng khoán  17/09/2025 14:59
4                                                                        Nếu mỗi ngày mua đúng 1 cổ phiếu VIC của Vingroup, sau 18 năm sẽ lãi hay lỗ?  16/09/2025 10:33
5                                                                Diễn biến mới tại dự án KCN 227ha do Vingroup đầu tư với tổng vốn trên 4.000 tỷ đồng  15/09/2025 08:58
6      Tỷ phú Phạm Nhật Vượng từng nói "chưa bán thì chưa mất, thị giá VIC sẽ trở lại": Vingroup sắp lấy lại vị trí lớn nhất TTCK từ tay Vietcombank?  15/09/2025 00:08
7                                                                         65 kênh đã ẩn, xóa 120 video bịa đặt, xuyên tạc, vu khống Tập đoàn Vingroup  12/09/2025 07:50
8                                                                                              Điều gì đằng sau những thông tin sai lệch về Vingroup?  10/09/2025 12:30
9                                                                     Khoản nợ 800.000 tỷ đồng bị thông tin thất thiệt của Vingroup có gì đáng chú ý?  09/09/2025 13:41
10                                                                                             Số nợ của Vingroup và nguyên tắc “vay được – trả được”  09/09/2025 11:30
11                                                                         3 lần tỷ phú Phạm Nhật Vượng là nạn nhân của những tin thất thiệt, bịa đặt  09/09/2025 10:06
12                                                                       Vingroup khởi kiện 68 tổ chức, cá nhân đưa thông tin sai sự thật về Tập đoàn  09/09/2025 07:33
13                                                            Rục rịch đưa "Gà đẻ trứng vàng" lên sàn, cổ phiếu loạt doanh nghiệp Việt tăng "bốc đầu"  08/09/2025 08:03
14                                                       Vingroup của tỷ phú Phạm Nhật Vượng bổ sung thêm 8 ngành nghề kinh doanh, tổng cộng 66 ngành  04/09/2025 13:39
15                                                                                                 Vingroup đạt bao nhiêu doanh thu từ mảng giáo dục?  04/09/2025 00:03
16                                                                                       Vingroup và thực tế con số nợ tài chính, doanh thu tương lai  04/09/2025 00:01
17                                                                                      Bất ngờ với mức thu nhập của ông Phạm Nhật Vượng tại Vingroup  03/09/2025 15:47
18                                                                              Vingroup công bố loạt tài liệu quan trọng đến người sở hữu trái phiếu  03/09/2025 14:41
19                                                           VIC: Giải trình biến động LNST trên BCTC bán niên 2025 soát xét so với cùng kỳ năm trước  03/09/2025 09:51
20                              Vingroup lãi gần 1.800 tỷ đồng từ việc bán Movian AI cho Qualcomm, bằng 16% lợi nhuận trước thuế 6 tháng đầu năm 2025  03/09/2025 07:57
21                                                                                                                 VIC: CBTT sáp nhập các công ty con  03/09/2025 00:00
22                                                                                      VIC: Giấy chứng nhận đăng ký doanh nghiệp thay đổi lần thứ 74  03/09/2025 00:00
23                                                                                                         VIC: CBTT về việc sáp nhập các công ty con  29/08/2025 00:00
24                    Công bố 10 tập đoàn đa ngành tư nhân nộp ngân sách lớn nhất Việt Nam: 9 DN có mảng bất động sản, 6 DN tham gia ngành năng lượng  28/08/2025 08:08
25                                                                                        VIC: CBTT về việc tiếp tục hỗ trợ tài chính cho công ty con  26/08/2025 00:00
26                                                                                                       VIC: Nghị quyết ĐHĐCĐ và Biên bản kiểm phiếu  26/08/2025 00:00
27                                                                                                 Vốn hóa Vingroup vượt 500.000 tỷ, cao nhất lịch sử  25/08/2025 10:46
28  Công bố 200 doanh nghiệp nộp ngân sách lớn nhất Việt Nam: Tổng nộp 794.000 tỷ đồng, Vingroup thu hẹp khoảng cách với vị trí số 1 của PetroVietnam  25/08/2025 08:08
29                                                                       VIC: Số lượng cổ phiếu có quyền biểu quyết đang lưu hành là 3.853.015.512 cp  21/08/2025 00:00

In [ ]:
df

            Thời gian                                            Tiêu đề
0    18/09/2025 11:22  Vingroup và tỷ phú Phạm Nhật Vượng vừa lập “cú...
1    18/09/2025 07:33  Từ ngày tỷ phú Phạm Nhật Vượng khuyên "chọn VI...
2    17/09/2025 15:57  Vingroup đạt được cột mốc chưa từng có trong g...
3    17/09/2025 14:59  Vingroup của tỷ phú Phạm Nhật Vượng vượt qua V...
4    16/09/2025 10:33  Nếu mỗi ngày mua đúng 1 cổ phiếu VIC của Vingr...
..                ...                                                ...
145  24/04/2025 09:56  ĐHCĐ Vingroup: Tháng 5 sẽ niêm yết Vinpearl, V...
146  21/04/2025 17:27                  VIC: Báo cáo thường niên năm 2024
147  18/04/2025 16:21                  Nhà đầu tư chốt lời cổ phiếu VIC?
148  17/04/2025 16:34  Vingroup chốt ngày chính thức động thổ Siêu dự...
149  17/04/2025 15:46           SK đã tìm được đối tác mua cổ phiếu VIC?

[150 rows x 2 columns]

In [ ]:
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Tạo thư mục cafef_news nếu chưa có
save_dir = "/content/drive/MyDrive/cafef_news"
os.makedirs(save_dir, exist_ok=True)

# # Đặt tên file (ví dụ theo ngày crawl)
# file_path = os.path.join(save_dir, "cafef_vic.csv")

# # Lưu DataFrame đã crawl
# df.to_csv(file_path, index=False, encoding="utf-8-sig")

# print(f" Đã lưu DataFrame vào: {file_path}")

Mounted at /content/drive

In [ ]:
!pip install selenium

Collecting selenium
  Downloading selenium-4.38.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: urllib3<3.0,>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (2.5.0)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.31.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: certifi>=2025.10.5 in /usr/local/lib/python3.12/dist-packages (from selenium) (2025.10.5)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (4.15.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.38.0-py3-none-any.whl (9.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 99.0 MB/s eta 0:00:00
Downloading trio-0.31.0-py3-none-any.whl (512 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 512.7/512.7 kB 34.5 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, outcome, trio, trio-websocket, selenium
Successfully installed outcome-1.3.0.post0 selenium-4.38.0 trio-0.31.0 trio-websocket-0.12.2 wsproto-1.2.0

In [ ]:
import pandas as pd
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException

# Hàm khởi tạo Edge driver
def init_driver():
    options = webdriver.EdgeOptions()
    options.add_argument("--headless")
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    driver = webdriver.Edge(options=options)
    return driver

def crawl_until_target(url, target_time, extra_pages):
    driver = init_driver()
    driver.get(url)

    data = []
    found_target = False
    extra_count = 0
    page_count = 0

    while True:
        page_count += 1
        print(f" Đang crawl trang {page_count} ...")

        posts = driver.find_elements(By.XPATH, '//*[@id="divEvents"]/ul/li')
        page_data = []

        for post in posts:
            try:
                time_text = post.find_element(By.XPATH, './span').text.strip()
                a_tag = post.find_element(By.XPATH, './a')
                title_text = a_tag.text.strip()
                url_path = a_tag.get_attribute("href")  # lấy link đầy đủ

                page_data.append({
                    'Thời gian': time_text,
                    'Tiêu đề': title_text,
                    'URL': url_path
                })

                # Nếu gặp bài báo mốc
                if time_text == target_time:
                    print(f" Đã gặp mốc {target_time} ở trang {page_count}")
                    found_target = True
            except NoSuchElementException:
                continue

        # Thêm dữ liệu trang hiện tại
        data.extend(page_data)

        # Nếu đã tìm thấy target
        if found_target:
            if extra_count >= extra_pages:
                print(f" Đã crawl thêm {extra_pages} trang sau mốc. Kết thúc.")
                break
            else:
                extra_count += 1
                print(f"Tiếp tục crawl trang bổ sung {extra_count}/{extra_pages}...")

        # Nhấn nút "Sau"
        try:
            next_button = driver.find_element(By.XPATH, '//*[@id="aNext"]')
            if next_button.is_displayed() and next_button.is_enabled():
                driver.execute_script("arguments[0].click();", next_button)
                time.sleep(2)  # chờ load nội dung mới
            else:
                print("Không còn nút 'Sau'. Dừng.")
                break
        except NoSuchElementException:
            print("Không tìm thấy nút 'Sau'. Dừng.")
            break

    driver.quit()
    return pd.DataFrame(data)


# --- Chạy thử ---
URL = "https://cafef.vn/du-lieu/tin-doanh-nghiep/vic/event.chn"
TARGET_TIME = "17/04/2025 15:46"   # mốc dừng
EXTRA_PAGES = 10                   # số trang bổ sung

df_new = crawl_until_target(URL, TARGET_TIME, EXTRA_PAGES)

print(f"\n Đã crawl tổng cộng {len(df_new)} bài trên {df_new['Thời gian'].nunique()} mốc thời gian")
print(df_new.head(10))   # Xem 10 bài đầu
print(df_new.tail(10))   # Xem 10 bài cuối

 Đang crawl trang 1 ...
 Đang crawl trang 2 ...
 Đang crawl trang 3 ...
 Đang crawl trang 4 ...
 Đang crawl trang 5 ...
 Đang crawl trang 6 ...
 Đã gặp mốc 17/04/2025 15:46 ở trang 6
Tiếp tục crawl trang bổ sung 1/10...
 Đang crawl trang 7 ...
Tiếp tục crawl trang bổ sung 2/10...
 Đang crawl trang 8 ...
Tiếp tục crawl trang bổ sung 3/10...
 Đang crawl trang 9 ...
Tiếp tục crawl trang bổ sung 4/10...
 Đang crawl trang 10 ...
Tiếp tục crawl trang bổ sung 5/10...
 Đang crawl trang 11 ...
Tiếp tục crawl trang bổ sung 6/10...
 Đang crawl trang 12 ...
Tiếp tục crawl trang bổ sung 7/10...
 Đang crawl trang 13 ...
Tiếp tục crawl trang bổ sung 8/10...
 Đang crawl trang 14 ...
Tiếp tục crawl trang bổ sung 9/10...
 Đang crawl trang 15 ...
Tiếp tục crawl trang bổ sung 10/10...
 Đang crawl trang 16 ...
 Đã crawl thêm 10 trang sau mốc. Kết thúc.

 Đã crawl tổng cộng 480 bài trên 423 mốc thời gian
          Thời gian                                            Tiêu đề  \
0  23/09/2025 11:34             Giải mã sức nóng của cổ phiếu Vingroup
1  23/09/2025 07:43  DA Cần Giờ 3 mặt giáp biển của Vingroup: Đầu t...
2  22/09/2025 15:14  Một doanh nghiệp muốn chia cổ tức khủng 330%, ...
3  22/09/2025 00:00                    VIC: CBTT thành lập công ty con
4  21/09/2025 20:57  Vingroup được chấp thuận dự án 21.400 tỷ đồng ...
5  20/09/2025 00:18  Tỷ phú Phạm Nhật Vượng giàu cỡ nào: Tài sản lớ...
6  19/09/2025 15:45  Vingroup lập kỷ lục mới, tỷ phú Phạm Nhật Vượn...
7  18/09/2025 11:22  Vingroup và tỷ phú Phạm Nhật Vượng vừa lập “cú...
8  18/09/2025 07:33  Từ ngày tỷ phú Phạm Nhật Vượng khuyên "chọn VI...
9  17/09/2025 15:57  Vingroup đạt được cột mốc chưa từng có trong g...

                                                 URL
0  https://cafef.vn/giai-ma-suc-nong-cua-co-phieu...
1  https://cafef.vn/da-can-gio-3-mat-giap-bien-cu...
2  https://cafef.vn/mot-doanh-nghiep-muon-chia-co...
3  https://cafef.vn/du-lieu/VIC-2301728/vic-cbtt-...
4  https://cafef.vn/vingroup-duoc-chap-thuan-du-a...
5  https://cafef.vn/ty-phu-pham-nhat-vuong-giau-c...
6  https://cafef.vn/vingroup-lap-ky-luc-moi-ty-ph...
7  https://cafef.vn/vingroup-va-ty-phu-pham-nhat-...
8  https://cafef.vn/tu-ngay-ty-phu-pham-nhat-vuon...
9  https://cafef.vn/vingroup-dat-duoc-cot-moc-chu...
            Thời gian                                            Tiêu đề  \
470  02/08/2023 00:08  Loạt DN "máu mặt" lãi lớn nhờ doanh thu tài ch...
471  02/08/2023 00:00  VIC: Chào bán trái phiếu ra công chúng - VICH2...
472  02/08/2023 00:00  VIC: Chào bán trái phiếu ra công chúng - VICH2...
473  01/08/2023 11:16  Taxi Xanh GSM và VMI - 2 công ty riêng của ông...
474  01/08/2023 11:02  Giải mã kỷ lục doanh thu 2 tỷ USD của Vingroup...
475  01/08/2023 10:34  Top doanh nghiệp lãi lớn nhất nửa đầu năm 2023...
476  31/07/2023 09:49  Dồn dập tin "nóng hổi" liên quan VinFast và kế...
477  31/07/2023 00:05  Vingroup: Lợi nhuận trước thuế 6 tháng tăng 12...
478  31/07/2023 00:00  VIC: Báo cáo tình hình quản trị Công ty 06 thá...
479  29/07/2023 00:48  VinFast đã khởi công giai đoạn 1 nhà máy sản x...

                                                   URL
470  https://cafef.vn/du-lieu/vic-1747600/loat-dn-m...
471  https://cafef.vn/du-lieu/vic-1749409/vic-chao-...
472  https://cafef.vn/du-lieu/vic-1749411/vic-chao-...
473  https://cafef.vn/du-lieu/vic-782356/taxi-xanh-...
474  https://cafef.vn/du-lieu/vic-782224/giai-ma-ky...
475  https://cafef.vn/du-lieu/vic-782038/top-doanh-...
476  https://cafef.vn/du-lieu/vic-780205/don-dap-ti...
477  https://cafef.vn/du-lieu/vic-779902/vingroup-l...
478  https://cafef.vn/du-lieu/vic-780981/vic-bao-ca...
479  https://cafef.vn/du-lieu/vic-778570/vinfast-da...

In [ ]:
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Tạo thư mục cafef_news nếu chưa có
save_dir = "/content/drive/MyDrive/cafef_news"
os.makedirs(save_dir, exist_ok=True)

# Đặt tên file (ví dụ theo ngày crawl)
file_path = os.path.join(save_dir, "cafef_vic.csv")

# Lưu DataFrame đã crawl
df_new.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_vic.csv

In [ ]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
import time

# Khởi tạo Edge driver
def init_driver():
    options = webdriver.EdgeOptions()
    options.add_argument("--headless")
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    driver = webdriver.Edge(options=options)
    return driver

def crawl_data(url, num_pages):
    driver = init_driver()
    driver.get(url)

    data = []
    print(f"Bắt đầu crawl {num_pages} trang từ: {url}")

    for i in range(num_pages):
        print(f"Trang {i+1}...")
        try:
            posts = driver.find_elements(By.XPATH, '//*[@id="divEvents"]/ul/li')

            for post in posts:
                try:
                    time_text = post.find_element(By.XPATH, './span').text.strip()
                    a_tag = post.find_element(By.XPATH, './a')
                    title_text = a_tag.text.strip()
                    link_url = a_tag.get_attribute("href")  # lấy URL

                    data.append({
                        'Thời gian': time_text,
                        'Tiêu đề': title_text,
                        'URL': link_url
                    })
                except NoSuchElementException:
                    continue

            # Nhấn nút "Sau" (AJAX load, không đổi URL)
            next_button = driver.find_element(By.XPATH, '//*[@id="aNext"]')
            if next_button.is_displayed() and next_button.is_enabled():
                driver.execute_script("arguments[0].click();", next_button)
                time.sleep(2)  # chờ dữ liệu mới load
            else:
                print("Không còn nút 'Sau'. Kết thúc.")
                break
        except NoSuchElementException:
            print("Không tìm thấy bài viết. Dừng lại.")
            break

    driver.quit()
    return pd.DataFrame(data)

# Crawl thử 5 trang
URL = "https://cafef.vn/du-lieu/tin-doanh-nghiep/hpg/event.chn"
NUM_PAGES = 25
df = crawl_data(URL, NUM_PAGES)

print("\nKết quả crawl:")
print(df.head(10))  # hiện 10 dòng đầu

Bắt đầu crawl 25 trang từ: https://cafef.vn/du-lieu/tin-doanh-nghiep/hpg/event.chn
Trang 1...
Trang 2...
Trang 3...
Trang 4...
Trang 5...
Trang 6...
Trang 7...
Trang 8...
Trang 9...
Trang 10...
Trang 11...
Trang 12...
Trang 13...
Trang 14...
Trang 15...
Trang 16...
Trang 17...
Trang 18...
Trang 19...
Trang 20...
Trang 21...
Trang 22...
Trang 23...
Trang 24...
Trang 25...

Kết quả crawl:
          Thời gian                                            Tiêu đề  \
0  17/09/2025 14:41  Mỗi ngày mua 1 cổ phiếu HPG của Hòa Phát: Hiệu...
1  17/09/2025 08:29  Nông nghiệp Hòa Phát chính thức nộp hồ sơ IPO,...
2  16/09/2025 00:09  Tỷ phú Trần Đình Long có động thái 'lạ' với nô...
3  13/09/2025 07:54  Công ty của Hòa Phát bổ sung hoạt động bán điệ...
4  11/09/2025 00:05  SSI dự báo lợi nhuận Hoà Phát nửa cuối năm 202...
5  08/09/2025 10:03  Hòa Phát sản xuất 31.800 tấn/ngày trong tháng ...
6  05/09/2025 00:03  Cổ phiếu tăng bốc đầu, tài sản ban lãnh đạo 1 ...
7  04/09/2025 11:54  Lò cao số 2 của Khu liên hợp gang thép Hòa Phá...
8  04/09/2025 09:57  Lộ diện 'chủ nợ' lớn nhất của Hoà Phát với kho...
9  03/09/2025 15:35  Hoà Phát nhận tin vui từ chính quyền cho dự án...

                                                 URL
0  https://cafef.vn/moi-ngay-mua-1-co-phieu-hpg-c...
1  https://cafef.vn/nong-nghiep-hoa-phat-chinh-th...
2  https://cafef.vn/ty-phu-tran-dinh-long-co-dong...
3  https://cafef.vn/cong-ty-cua-hoa-phat-bo-sung-...
4  https://cafef.vn/ssi-du-bao-loi-nhuan-hoa-phat...
5  https://cafef.vn/hoa-phat-san-xuat-31800-tanng...
6  https://cafef.vn/co-phieu-tang-boc-dau-tai-san...
7  https://cafef.vn/lo-cao-so-2-cua-khu-lien-hop-...
8  https://cafef.vn/lo-dien-chu-no-lon-nhat-cua-h...
9  https://cafef.vn/hoa-phat-nhan-tin-vui-tu-chin...

In [ ]:
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Tạo thư mục cafef_news nếu chưa có
save_dir = "/content/drive/MyDrive/cafef_news"
os.makedirs(save_dir, exist_ok=True)

# Đặt tên file (ví dụ theo ngày crawl)
# file_path = os.path.join(save_dir, "cafef_hpg.csv")

# # Lưu DataFrame đã crawl
# df_new.to_csv(file_path, index=False, encoding="utf-8-sig")

# print(f" Đã lưu DataFrame vào: {file_path}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
import time

# Khởi tạo Edge driver
def init_driver():
    options = webdriver.EdgeOptions()
    options.add_argument("--headless")
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    driver = webdriver.Edge(options=options)
    return driver

def crawl_data(url, num_pages):
    driver = init_driver()
    driver.get(url)

    data = []
    print(f"Bắt đầu crawl {num_pages} trang từ: {url}")

    for i in range(num_pages):
        print(f"Trang {i+1}...")
        try:
            posts = driver.find_elements(By.XPATH, '//*[@id="divEvents"]/ul/li')

            for post in posts:
                try:
                    time_text = post.find_element(By.XPATH, './span').text.strip()
                    a_tag = post.find_element(By.XPATH, './a')
                    title_text = a_tag.text.strip()
                    link_url = a_tag.get_attribute("href")  # lấy URL

                    data.append({
                        'Thời gian': time_text,
                        'Tiêu đề': title_text,
                        'URL': link_url
                    })
                except NoSuchElementException:
                    continue

            # Nhấn nút "Sau" (AJAX load, không đổi URL)
            next_button = driver.find_element(By.XPATH, '//*[@id="aNext"]')
            if next_button.is_displayed() and next_button.is_enabled():
                driver.execute_script("arguments[0].click();", next_button)
                time.sleep(2)  # chờ dữ liệu mới load
            else:
                print("Không còn nút 'Sau'. Kết thúc.")
                break
        except NoSuchElementException:
            print("Không tìm thấy bài viết. Dừng lại.")
            break

    driver.quit()
    return pd.DataFrame(data)

# Crawl thử 5 trang
URL = "https://cafef.vn/du-lieu/tin-doanh-nghiep/fpt/event.chn"
NUM_PAGES = 25
df = crawl_data(URL, NUM_PAGES)

print("\nKết quả crawl:")
print(df.head(10))  # hiện 10 dòng đầu

Bắt đầu crawl 25 trang từ: https://cafef.vn/du-lieu/tin-doanh-nghiep/fpt/event.chn
Trang 1...
Trang 2...
Trang 3...
Trang 4...
Trang 5...
Trang 6...
Trang 7...
Trang 8...
Trang 9...
Trang 10...
Trang 11...
Trang 12...
Trang 13...
Trang 14...
Trang 15...
Trang 16...
Trang 17...
Trang 18...
Trang 19...
Trang 20...
Trang 21...
Trang 22...
Trang 23...
Trang 24...
Trang 25...

Kết quả crawl:
          Thời gian                                            Tiêu đề  \
0  23/09/2025 08:13  Ông Donald Trump tuyên bố áp 100.000 USD cho v...
1  18/09/2025 11:22  FPT hoàn thành tăng vốn điều lệ lên hơn 17 ngh...
2  16/09/2025 17:30  Tập đoàn công nghệ hàng đầu Việt Nam vừa có bả...
3  16/09/2025 13:49  FPT ký kết hợp tác AI mở ra cơ hội lên đến 30 ...
4  16/09/2025 08:00  FPT ký hợp đồng kỷ lục 256 triệu USD với tập đ...
5  16/09/2025 00:10  FPT báo lãi ròng gần 6.000 tỷ, doanh thu khối ...
6  04/09/2025 00:00  FPT: 12.9.2025, giao dịch 222.176.999 cp niêm ...
7  04/09/2025 00:00  FPT: Anh rể ông Trương Gia Bình - Chủ tịch HĐQ...
8  28/08/2025 00:00    FPT: 29.8.2025, niêm yết bổ sung 222.176.999 cp
9  27/08/2025 15:51  Sau khi nhận nhiệm vụ từ Thủ tướng, ông Trương...

                                                 URL
0  https://cafef.vn/ong-donald-trump-tuyen-bo-ap-...
1  https://cafef.vn/fpt-hoan-thanh-tang-von-dieu-...
2  https://cafef.vn/tap-doan-cong-nghe-hang-dau-v...
3  https://cafef.vn/fpt-ky-ket-hop-tac-ai-mo-ra-c...
4  https://cafef.vn/fpt-ky-hop-dong-ky-luc-256-tr...
5  https://cafef.vn/fpt-bao-lai-rong-gan-6000-ty-...
6  https://cafef.vn/du-lieu/FPT-2289776/fpt-12920...
7  https://cafef.vn/du-lieu/FPT-2290683/fpt-anh-r...
8  https://cafef.vn/du-lieu/FPT-2288129/fpt-29820...
9  https://cafef.vn/sau-khi-nhan-nhiem-vu-tu-thu-...

In [ ]:
file_path = os.path.join(save_dir, "cafef_fpt.csv")

# Lưu DataFrame đã crawl
df_new.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_fpt.csv

In [ ]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
import time

# Khởi tạo Edge driver
def init_driver():
    options = webdriver.EdgeOptions()
    options.add_argument("--headless")
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    driver = webdriver.Edge(options=options)
    return driver

def crawl_data(url, num_pages):
    driver = init_driver()
    driver.get(url)

    data = []
    print(f"Bắt đầu crawl {num_pages} trang từ: {url}")

    for i in range(num_pages):
        print(f"Trang {i+1}...")

        try:
            # Lấy tất cả các bài trong list
            posts = driver.find_elements(By.XPATH, '//*[@id="divTopEvents"]/ul/li')

            for post in posts:
                try:
                    a_tag = post.find_element(By.XPATH, './a')
                    title_text = a_tag.text.strip()
                    link_url = a_tag.get_attribute("href")

                    # Thời gian nếu có
                    try:
                        time_text = post.find_element(By.XPATH, './/span').text.strip()
                    except NoSuchElementException:
                        time_text = ""

                    data.append({
                        'Thời gian': time_text,
                        'Tiêu đề': title_text,
                        'URL': link_url
                    })
                except NoSuchElementException:
                    continue

            # Nhấn nút "Sau"
            try:
                next_button = driver.find_element(By.XPATH, '//*[@id="spanNext"]')
                if next_button.is_displayed() and next_button.is_enabled():
                    driver.execute_script("arguments[0].click();", next_button)
                    time.sleep(2)
                else:
                    print("Không còn nút 'Sau'. Kết thúc.")
                    break
            except NoSuchElementException:
                print("Không tìm thấy nút 'Sau'. Kết thúc.")
                break

        except NoSuchElementException:
            print("Không tìm thấy bài viết. Dừng lại.")
            break

    driver.quit()
    return pd.DataFrame(data)

# Crawl thử
URL = "https://cafef.vn/du-lieu/hose/vcb-ngan-hang-thuong-mai-co-phan-ngoai-thuong-viet-nam.chn"
NUM_PAGES = 15
df = crawl_data(URL, NUM_PAGES)

print("\nKết quả crawl:")
print(df.head(10))

Bắt đầu crawl 15 trang từ: https://cafef.vn/du-lieu/hose/vcb-ngan-hang-thuong-mai-co-phan-ngoai-thuong-viet-nam.chn
Trang 1...
Trang 2...
Trang 3...
Trang 4...
Trang 5...
Trang 6...
Trang 7...
Trang 8...
Trang 9...
Trang 10...
Trang 11...
Trang 12...
Trang 13...
Trang 14...
Trang 15...

Kết quả crawl:
            Thời gian                                            Tiêu đề  \
0  (24/10/2025 07:32)  Những DN lớn nhất: Chỉ Vinamilk và ACV trả lươ...
1  (15/10/2025 00:00)  VCB: HĐQT phê duyệt chủ trương giao dịch với V...
2  (07/10/2025 07:52)  'Đế chế' của ông Phạm Nhật Vượng chỉ có 37,3% ...
3  (02/10/2025 00:00)  VCB: Nghị quyết HĐQT phê duyệt chủ trương thay...
4  (01/10/2025 10:06)  Vietcombank dự chi gần 3.800 tỷ đồng trả cổ tứ...
5  (30/09/2025 00:00)  VCB: 3.10.2025, ngày GDKHQ trả cổ tức năm 2024...
6  (24/10/2025 07:32)  Những DN lớn nhất: Chỉ Vinamilk và ACV trả lươ...
7  (15/10/2025 00:00)  VCB: HĐQT phê duyệt chủ trương giao dịch với V...
8  (07/10/2025 07:52)  'Đế chế' của ông Phạm Nhật Vượng chỉ có 37,3% ...
9  (02/10/2025 00:00)  VCB: Nghị quyết HĐQT phê duyệt chủ trương thay...

                                                 URL
0  https://cafef.vn/nhung-dn-lon-nhat-chi-vinamil...
1  https://cafef.vn/du-lieu/VCB-2317587/vcb-hdqt-...
2  https://cafef.vn/de-che-cua-ong-pham-nhat-vuon...
3  https://cafef.vn/du-lieu/VCB-2309145/vcb-nghi-...
4  https://cafef.vn/vietcombank-du-chi-gan-3800-t...
5  https://cafef.vn/du-lieu/VCB-2307531/vcb-31020...
6  https://cafef.vn/nhung-dn-lon-nhat-chi-vinamil...
7  https://cafef.vn/du-lieu/VCB-2317587/vcb-hdqt-...
8  https://cafef.vn/de-che-cua-ong-pham-nhat-vuon...
9  https://cafef.vn/du-lieu/VCB-2309145/vcb-nghi-...

In [ ]:
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Tạo thư mục cafef_news nếu chưa có
save_dir = "/content/drive/MyDrive/cafef_news/SSI_related_com"
os.makedirs(save_dir, exist_ok=True)

Mounted at /content/drive

In [ ]:
file_path = os.path.join(save_dir, "cafef_fpt_1.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_fpt_1.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_dgc_1.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_dgc_1.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_gas_1.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_gas_1.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_hpg_1.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_hpg_1.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_msn_1.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_msn_1.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_sab_1.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_sab_1.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_ssi_1.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_ssi_1.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_vic_1.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_vic_1.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_vnm_1.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_vnm_1.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_acb_1.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_acb_1.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_dgc.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_dgc.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_ssi.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_ssi.csv

In [ ]:
file_path = os.path.join(save_dir, "VCB.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/SSI_related_com/VCB.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_gas.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_gas.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_vnm.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_vnm.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_msn.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_msn.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_sab.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_sab.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_fpt.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_fpt.csv

In [ ]:
file_path = os.path.join(save_dir, "cafef_hpg.csv")

# Lưu DataFrame đã crawl
df.to_csv(file_path, index=False, encoding="utf-8-sig")

print(f" Đã lưu DataFrame vào: {file_path}")

 Đã lưu DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_hpg.csv

Crawl tiếp 10 trang tiếp theo

In [ ]:
pip install selenium

Collecting selenium
  Downloading selenium-4.35.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: urllib3<3.0,>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (2.5.0)
Collecting trio~=0.30.0 (from selenium)
  Downloading trio-0.30.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket~=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: certifi>=2025.6.15 in /usr/local/lib/python3.12/dist-packages (from selenium) (2025.8.3)
Collecting typing_extensions~=4.14.0 (from selenium)
  Downloading typing_extensions-4.14.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: websocket-client~=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio~=0.30.0->selenium) (25.3.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio~=0.30.0->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio~=0.30.0->selenium) (3.10)
Collecting outcome (from trio~=0.30.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio~=0.30.0->selenium) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket~=0.12.2->selenium)
  Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket~=0.12.2->selenium) (0.16.0)
Downloading selenium-4.35.0-py3-none-any.whl (9.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 48.9 MB/s eta 0:00:00
Downloading trio-0.30.0-py3-none-any.whl (499 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 499.2/499.2 kB 22.3 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading typing_extensions-4.14.1-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.9/43.9 kB 2.2 MB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, typing_extensions, outcome, trio, trio-websocket, selenium
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.15.0
    Uninstalling typing_extensions-4.15.0:
      Successfully uninstalled typing_extensions-4.15.0
Successfully installed outcome-1.3.0.post0 selenium-4.35.0 trio-0.30.0 trio-websocket-0.12.2 typing_extensions-4.14.1 wsproto-1.2.0

In [ ]:
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Tạo thư mục cafef_news nếu chưa có
save_dir = "/content/drive/MyDrive/cafef_news"
os.makedirs(save_dir, exist_ok=True)

# # Đặt tên file (ví dụ theo ngày crawl)
# file_path = os.path.join(save_dir, "cafef_fpt.csv")

# # Nếu file đã tồn tại thì không ghi header nữa
# if os.path.exists(file_path):
#     df_new.to_csv(file_path, mode='a', header=False, index=False, encoding="utf-8-sig")
# else:
#     df_new.to_csv(file_path, mode='w', header=True, index=False, encoding="utf-8-sig")

# print(f" Đã nối thêm DataFrame vào: {file_path}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Đặt tên file (ví dụ theo ngày crawl)
file_path = os.path.join(save_dir, "cafef_hpg.csv")

# Nếu file đã tồn tại thì không ghi header nữa
if os.path.exists(file_path):
    df_new.to_csv(file_path, mode='a', header=False, index=False, encoding="utf-8-sig")
else:
    df_new.to_csv(file_path, mode='w', header=True, index=False, encoding="utf-8-sig")

print(f" Đã nối thêm DataFrame vào: {file_path}")

 Đã nối thêm DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_hpg.csv

In [ ]:
# Đặt tên file (ví dụ theo ngày crawl)
file_path = os.path.join(save_dir, "cafef_msn.csv")

# Nếu file đã tồn tại thì không ghi header nữa
if os.path.exists(file_path):
    df_new.to_csv(file_path, mode='a', header=False, index=False, encoding="utf-8-sig")
else:
    df_new.to_csv(file_path, mode='w', header=True, index=False, encoding="utf-8-sig")

print(f" Đã nối thêm DataFrame vào: {file_path}")

 Đã nối thêm DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_msn.csv

In [ ]:
# Đặt tên file (ví dụ theo ngày crawl)
file_path = os.path.join(save_dir, "cafef_vic.csv")

# Nếu file đã tồn tại thì không ghi header nữa
if os.path.exists(file_path):
    df_new.to_csv(file_path, mode='a', header=False, index=False, encoding="utf-8-sig")
else:
    df_new.to_csv(file_path, mode='w', header=True, index=False, encoding="utf-8-sig")

print(f" Đã nối thêm DataFrame vào: {file_path}")

 Đã nối thêm DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_vic.csv

In [ ]:
# Đặt tên file (ví dụ theo ngày crawl)
file_path = os.path.join(save_dir, "cafef_vnm.csv")

# Nếu file đã tồn tại thì không ghi header nữa
if os.path.exists(file_path):
    df_new.to_csv(file_path, mode='a', header=False, index=False, encoding="utf-8-sig")
else:
    df_new.to_csv(file_path, mode='w', header=True, index=False, encoding="utf-8-sig")

print(f" Đã nối thêm DataFrame vào: {file_path}")

 Đã nối thêm DataFrame vào: /content/drive/MyDrive/cafef_news/cafef_vnm.csv

Crawl nội dung bài báo

In [ ]:
from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Kiểm tra thư mục cafef_news
save_dir = "/content/drive/MyDrive/cafef_news"
os.makedirs(save_dir, exist_ok=True)

print(" Google Drive đã được mount.")

Mounted at /content/drive
 Google Drive đã được mount.

In [ ]:
import pandas as pd
import time
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException

# --- Khởi tạo Edge driver ---
def init_driver():
    options = webdriver.EdgeOptions()
    options.add_argument("--headless")
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    driver = webdriver.Edge(options=options)
    return driver

# --- Hàm crawl nội dung 1 bài báo ---
def crawl_article_content(url):
    driver = init_driver()
    try:
        driver.get(url)
        time.sleep(2)  # chờ load trang

        content_texts = []

        # Lấy sapo (nếu có)
        try:
            sapo = driver.find_element(
                By.XPATH, "/html/body/div[2]/div[2]/div[2]/div[1]/div/div[1]/div[5]/h2"
            ).text.strip()
            if sapo:
                content_texts.append(sapo)
        except NoSuchElementException:
            pass

        # Lấy các đoạn văn bản align-justify
        try:
            paras = driver.find_elements(By.XPATH, '//*[@id="mainContent"]//p[@class="align-justify"]')
            for p in paras:
                txt = p.text.strip()
                if txt:
                    content_texts.append(txt)

            # fallback nếu chưa có đoạn nào
            if not content_texts:
                paras = driver.find_elements(By.XPATH, '//*[@id="mainContent"]/div/p')
                for p in paras:
                    txt = p.text.strip()
                    if txt:
                        content_texts.append(txt)
        except NoSuchElementException:
            pass

        return "\n".join(content_texts) if content_texts else None

    except Exception as e:
        print(f" Lỗi khi crawl {url}: {e}")
        return None
    finally:
        driver.quit()

# --- Đọc file CSV ---
file_path = "/content/drive/MyDrive/cafef_news/cafef_vnm.csv"

# Check if the file exists before attempting to read it
if not os.path.exists(file_path):
    print(f"Error: File not found at {file_path}")
else:
    df = pd.read_csv(file_path)

    # Nếu chưa có cột "Nội dung" thì thêm
    if "Nội dung" not in df.columns:
        df["Nội dung"] = None

    # --- Crawl cho từng URL ---
    for i, row in df.iterrows():
        if pd.isna(row["Nội dung"]) or not row["Nội dung"]:  # chỉ crawl nếu chưa có
            url = row["URL"]
            print(f" Crawl {i+1}/{len(df)}: {url}")
            content = crawl_article_content(url)
            df.at[i, "Nội dung"] = content

            # Lưu tạm sau mỗi bài để tránh mất dữ liệu
            df.to_csv(file_path, index=False, encoding="utf-8-sig")

    print(f"\n Đã cập nhật nội dung vào file: {file_path}")

 Crawl 1/1050: https://cafef.vn/du-lieu/VNM-2297896/vnm-cong-ty-tnhh-mtv-dau-tu-scic-sic-dang-ky-ban-1450000-cp.chn
 Crawl 2/1050: https://cafef.vn/du-lieu/VNM-2290688/vnm-platinum-victory-pte-ltd-chua-mua-cp.chn
 Crawl 3/1050: https://cafef.vn/du-lieu/VNM-2290690/vnm-platinum-victory-pte-ltd-dang-ky-mua-20899554-cp.chn
 Crawl 4/1050: https://cafef.vn/du-lieu/VNM-2290806/vnm-cong-ty-tnhh-mot-thanh-vien-dau-tu-scic-sic-chua-ban-cp.chn
 Crawl 5/1050: https://cafef.vn/du-lieu/VNM-2290574/vnm-fn-dairy-investments-pteltd-cdl-chua-mua-cp.chn
 Crawl 6/1050: https://cafef.vn/du-lieu/VNM-2290579/vnm-fn-dairy-investments-pteltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 7/1050: https://cafef.vn/tap-doan-chi-hang-ty-usd-vao-thaco-vinamilk-ree-bao-lai-rong-nua-dau-nam-2025-giam-23-thi-truong-viet-nam-toa-sang-lai-tu-ree-tang-gan-50-188250829224928494.chn
 Crawl 8/1050: https://cafef.vn/nhung-dai-gia-dem-tien-mat-di-tra-het-no-van-con-hon-chuc-nghin-ty-188250819071520593.chn
 Crawl 9/1050: https://cafef.vn/cong-bo-100-doanh-nghiep-tu-nhan-nop-ngan-sach-lon-nhat-viet-nam-tong-nop-244400-ty-dong-48-don-vi-nop-tren-nghin-ty-188250817184036191.chn
 Crawl 10/1050: https://cafef.vn/du-lieu/VNM-2277554/vnm-giay-chung-nhan-dang-ky-doanh-nghiep-thay-doi-lan-thu-30.chn
 Crawl 11/1050: https://cafef.vn/o-at-tung-san-pham-moi-vinamilk-don-luong-khach-ky-luc-du-kien-tang-so-cua-hang-tu-600-len-800-ngay-trong-nam-nay-188250807075006088.chn
 Crawl 12/1050: https://cafef.vn/du-lieu/VNM-2282483/vnm-giai-trinh-kqkd-hop-nhat-va-rieng-6-thang-nam-2025-so-voi-cung-ky-nam-truoc.chn
 Crawl 13/1050: https://cafef.vn/du-lieu/VNM-2265316/vnm-cong-ty-tnhh-mtv-dau-tu-scic-sic-dang-ky-ban-1450000-cp.chn
 Crawl 14/1050: https://cafef.vn/du-lieu/VNM-2265328/vnm-platinum-victory-pte-ltd-chua-mua-cp.chn
 Crawl 15/1050: https://cafef.vn/du-lieu/VNM-2265329/vnm-platinum-victory-pte-ltd-dang-ky-mua-20899554-cp.chn
 Crawl 16/1050: https://cafef.vn/du-lieu/VNM-2265393/vnm-fn-dairy-investments-pte-ltd-chua-mua-cp.chn
 Crawl 17/1050: https://cafef.vn/du-lieu/VNM-2265396/vnm-fn-dairy-investments-pte-ltd-dang-ky-mua-20899554-cp.chn
 Crawl 18/1050: https://cafef.vn/du-lieu/VNM-2270885/vnm-bao-cao-tinh-hinh-quan-tri-cong-ty-06-thang-dau-nam-2025.chn
 Crawl 19/1050: https://cafef.vn/ctck-chi-ra-15-co-phieu-co-the-hut-tien-manh-khi-nang-hang-tam-diem-nhom-vingroup-188250713231056485.chn
 Crawl 20/1050: https://cafef.vn/ba-mai-kieu-lien-tang-truong-2-chu-so-ve-doanh-thu-thi-kho-nhung-tang-ve-nang-suat-va-thu-nhap-nguoi-lao-dong-thi-lam-duoc-188250711082539119.chn
 Crawl 21/1050: https://cafef.vn/cuoc-dua-von-hoa-25-nam-mot-cong-ty-thuy-dien-tung-giu-ngoi-vua-truoc-khi-nhung-ga-khong-lo-fpt-vinamilk-vietcombank-tran-len-san-188250702070405395.chn
 Crawl 22/1050: https://cafef.vn/du-lieu/VNM-2233655/vnm-fn-diary-investments-pteltd-chua-mua-cp.chn
 Crawl 23/1050: https://cafef.vn/du-lieu/VNM-2233678/vnm-fn-diary-investments-pteltd-dang-ky-mua-20899554-cp.chn
 Crawl 24/1050: https://cafef.vn/du-lieu/VNM-2230590/vnm-platinum-victory-pte-ptd-chua-mua-cp.chn
 Crawl 25/1050: https://cafef.vn/du-lieu/VNM-2230777/vnm-platinum-victory-pte-ltd-dang-ky-mua-20899554-cp.chn
 Crawl 26/1050: https://cafef.vn/du-lieu/VNM-2227985/vnm-thong-bao-ky-ket-hop-dong-kiem-toan-bctc-2025.chn
 Crawl 27/1050: https://cafef.vn/vinamilk-20-nam-tham-gia-hoi-cho-fb-lon-nhat-chau-a-kiem-duoc-nhung-hop-dong-trung-thanh-hang-thap-ky-tu-san-pham-khong-phai-the-manh-cua-viet-nam-188250604120656019.chn
 Crawl 28/1050: https://cafef.vn/du-lieu/VNM-2207757/vnm-fn-dairy-investments-pteltd-cdl-chua-mua-cp.chn
 Crawl 29/1050: https://cafef.vn/du-lieu/VNM-2207760/vnm-fn-dairy-investments-pteltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 30/1050: https://cafef.vn/du-lieu/VNM-2204019/vnm-thong-bao-lua-chon-don-vi-kiem-toan-doc-lap-cho-nam-2025.chn
 Crawl 31/1050: https://cafef.vn/du-lieu/vnm-2204154/vnm-platinum-victory-pte-ltd-cdl-chua-mua-cp.chn
 Crawl 32/1050: https://cafef.vn/du-lieu/vnm-2204156/vnm-platinum-victory-pte-ltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 33/1050: https://cafef.vn/du-lieu/vnm-2195234/hoa-phat-duc-giang-vinamilk-se-chi-them-bao-nhieu-sau-khi-gia-dien-dieu-chinh-tang-48.chn
 Crawl 34/1050: https://cafef.vn/du-lieu/vnm-2201475/vnm-dieu-le-cong-ty-cap-nhat-2025.chn
 Crawl 35/1050: https://cafef.vn/du-lieu/vnm-2227323/vnm-thong-bao-ve-ngay-dang-ky-cuoi-cung-chi-tra-lan-1-co-tuc-con-lai-cua-nam-2024-bang-tien-mat.chn
 Crawl 36/1050: https://cafef.vn/du-lieu/vnm-2193171/vnm-1452025-ngay-gdkhq-chi-tra-lan-1-co-tuc-con-lai-cua-nam-2024-bang-tien-mat-2000-dcp.chn
 Crawl 37/1050: https://cafef.vn/du-lieu/vnm-2196357/vnm-phan-cong-nhiem-vu-thanh-vien-hdqt.chn
 Crawl 38/1050: https://cafef.vn/du-lieu/vnm-2188943/co-dong-vinamilk-sap-nhan-hon-4000-ty-dong-tien-co-tuc-chot-danh-sach-trong-thang-5.chn
 Crawl 39/1050: https://cafef.vn/du-lieu/vnm-2195554/vnm-cbtt-chi-tra-co-tuc-con-lai-nam-2024.chn
 Crawl 40/1050: https://cafef.vn/du-lieu/vnm-2221923/vnm-giai-trinh-loi-nhuan-sau-thue-quy-12025-so-voi-quy-12024.chn
 Crawl 41/1050: https://cafef.vn/du-lieu/vnm-2221999/vnm-bo-nhiem-ong-vu-tri-thuc-ba-tongjai-thanachanan-lam-thanh-vien-hdqt-tu-2542025.chn
 Crawl 42/1050: https://cafef.vn/du-lieu/vnm-2195261/vnm-nghi-quyet-va-bien-ban-hop-dhdcd-thuong-nien-nam-2025.chn
 Crawl 43/1050: https://cafef.vn/du-lieu/vnm-2186309/vnm-fn-dairy-investments-pteltd-cdl-chua-mua-cp.chn
 Crawl 44/1050: https://cafef.vn/du-lieu/vnm-2186310/vnm-fn-dairy-investments-pteltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 45/1050: https://cafef.vn/du-lieu/vnm-2176011/vnm-platinum-victory-pte-ltd-chua-mua-cp.chn
 Crawl 46/1050: https://cafef.vn/du-lieu/vnm-2176012/vnm-platinum-victory-pte-ltd-dang-ky-mua-20899554-cp.chn
 Crawl 47/1050: https://cafef.vn/du-lieu/vnm-2176010/vnm-link-cong-bo-danh-sach-ung-vien-bau-bo-sung-cho-vi-tri-thanh-vien-hdqt-nhiem-ky-20222026.chn
 Crawl 48/1050: https://cafef.vn/du-lieu/vnm-2168642/cac-dn-co-ty-trong-doanh-thu-xuat-khau-lon-nhat-san-chung-khoan-hoa-phat-hoa-sen-vinamilk-fpt-masan-xuat-hien-o-dau.chn
 Lỗi khi crawl https://cafef.vn/du-lieu/vnm-2168642/cac-dn-co-ty-trong-doanh-thu-xuat-khau-lon-nhat-san-chung-khoan-hoa-phat-hoa-sen-vinamilk-fpt-masan-xuat-hien-o-dau.chn: HTTPConnectionPool(host='localhost', port=50715): Read timed out. (read timeout=120)
 Crawl 49/1050: https://cafef.vn/du-lieu/vnm-2161502/vnm-link-cong-bo-tai-lieu-hop-dhdcd-thuong-nien-nam-2025.chn
 Crawl 50/1050: https://cafef.vn/du-lieu/vnm-2160457/vinamilk-dat-ke-hoach-doanh-thu-nam-2025-len-dinh-moi-nang-co-tuc-tien-mat-nam-2024-len-435.chn
 Crawl 51/1050: https://cafef.vn/du-lieu/vnm-2159150/vnm-don-xin-tu-nhiem-cua-ong-hoang-ngoc-thach-thanh-vien-hdqt.chn
 Crawl 52/1050: https://cafef.vn/du-lieu/vnm-2156626/vinamilk-dieu-chinh-giam-chi-phi-quang-cao-tang-khuyen-mai-gioi-thieu-san-pham-thuc-day-ban-hang.chn
 Crawl 53/1050: https://cafef.vn/du-lieu/vnm-2155276/vinamilk-lo-dien-20-ndt-lon-nhat-nam-758-co-phan-co-su-hien-hien-cua-mot-loat-ca-map-hang-dau-the-gioi.chn
 Crawl 54/1050: https://cafef.vn/du-lieu/vnm-2154966/ung-tuyen-vinamilk-kho-ngang-dai-hoc-danh-tieng-ty-le-choi-1342-cho-mot-vi-tri.chn
 Crawl 55/1050: https://cafef.vn/du-lieu/vnm-2154043/vnm-fn-dairy-investments-pteltd-chua-mua-cp.chn
 Crawl 56/1050: https://cafef.vn/du-lieu/vnm-2154050/vnm-fn-dairy-investments-pteltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 57/1050: https://cafef.vn/du-lieu/vnm-2149157/vnm-platinum-victory-pte-ltd-cdl-chua-mua-cp.chn
 Crawl 58/1050: https://cafef.vn/du-lieu/vnm-2149158/vnm-platinum-victory-pte-ltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 59/1050: https://cafef.vn/du-lieu/vnm-2143372/chung-khoan-viet-nam-sang-cua-duoc-nang-hang-co-phieu-du-suc-don-dong-tien-lon-tuong-nhieu-ma-it.chn
 Crawl 60/1050: https://cafef.vn/du-lieu/vnm-2137231/vnm-thong-bao-don-xin-tu-nhiem-cua-ong-lee-meng-tat-thanh-vien-hdqt.chn
 Crawl 61/1050: https://cafef.vn/du-lieu/vnm-2132140/vnm-fn-dairy-investments-pteltd-cdl-chua-mua-cp.chn
 Crawl 62/1050: https://cafef.vn/du-lieu/vnm-2132147/vnm-fn-dairy-investments-pte-ltd-dang-ky-mua-20899554-cp.chn
 Crawl 63/1050: https://cafef.vn/du-lieu/vnm-2128233/vnm-1732025-ngay-gdkhq-to-chuc-dhdcd-thuong-nien-nam-2025.chn
 Crawl 64/1050: https://cafef.vn/du-lieu/vnm-2135892/top-50-loi-nhuan-2024-van-la-cuoc-ap-dao-cua-ngan-hang-va-bds-bsr-kbc-hag-nvl-bien-mat-trong-khi-2-cong-ty-ho-gelex-troi-day.chn
 Crawl 65/1050: https://cafef.vn/du-lieu/vnm-2125718/vnm-platinum-victory-pte-ltd-cdl-chua-mua-cp.chn
 Crawl 66/1050: https://cafef.vn/du-lieu/vnm-2125720/vnm-platinum-victory-pte-ltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 67/1050: https://cafef.vn/du-lieu/vnm-2124726/vnm-nghi-quyet-hdqt-thong-qua-viec-to-chuc-dhdcd-thuong-nien-nam-2025.chn
 Crawl 68/1050: https://cafef.vn/du-lieu/vnm-2120869/vinamilk-can-dich-2024-doanh-thu-nuoc-ngoai-tang-truong-2-chu-so-tiep-tuc-dan-dau-thi-phan-noi-dia.chn
 Crawl 69/1050: https://cafef.vn/du-lieu/vnm-2119932/vnm-bao-cao-tinh-hinh-quan-tri-cong-ty-nam-2024.chn
 Crawl 70/1050: https://cafef.vn/du-lieu/vnm-2135310/masan-chi-1600-ty-mua-5-tang-lau-quan-1-cua-techcombank-lam-phi-thuyen-vu-tru-acv-va-vietjet-lap-quan-hang-khong-tai-tan-binh.chn
 Crawl 71/1050: https://cafef.vn/du-lieu/vnm-2115154/ty-phu-thai-lan-quyet-tam-theo-duoi-vinamilk-sau-thuong-vu-chi-5-ty-usd-thau-tom-sabeco.chn
 Crawl 72/1050: https://cafef.vn/du-lieu/vnm-2114947/vnm-fn-dairy-investments-pteltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 73/1050: https://cafef.vn/du-lieu/vnm-2114952/vnm-fn-dairy-investments-pteltd-chua-mua-cp.chn
 Crawl 74/1050: https://cafef.vn/du-lieu/vnm-2114193/sau-6-nam-thau-tom-voi-4-lan-tang-von-vinamilk-rot-hon-2164-ty-dong-dau-tu-trang-trai-bo-sua-25000-ha-tai-lao.chn
 Crawl 75/1050: https://cafef.vn/du-lieu/vnm-2113698/gan-nua-the-ky-kien-dinh-mot-su-menh-cham-soc-thuong-hieu-quoc-gia-vinamilk-vung-vang-vuon-minh-cung-viet-nam.chn
 Crawl 76/1050: https://cafef.vn/du-lieu/vnm-2108306/vinamilk-ngung-lien-doanh-tai-philippines.chn
 Crawl 77/1050: https://cafef.vn/du-lieu/vnm-2108777/vnm-hdqt-thong-qua-viec-ngung-lien-doanh-tai-philippines.chn
 Crawl 78/1050: https://cafef.vn/du-lieu/vnm-2109179/vnm-platinum-victory-pte-ltd-chua-mua-cp.chn
 Crawl 79/1050: https://cafef.vn/du-lieu/vnm-2109180/vnm-platinum-victory-pte-ltd-dang-ky-mua-20899554-cp.chn
 Crawl 80/1050: https://cafef.vn/du-lieu/vnm-2107242/vnm-nghi-quyet-hdqt-bo-nhiem-chinh-thuc-vi-tri-giam-doc-dieu-hanh-phat-trien-vung-nguyen-lieu.chn
 Crawl 81/1050: https://cafef.vn/du-lieu/vnm-2106958/vnm-bo-nhiem-ong-doan-quoc-khanh-giu-chuc-giam-doc-dieu-hanh-phat-trien-vung-nguyen-lieu-tu-112025.chn
 Crawl 82/1050: https://cafef.vn/du-lieu/vnm-2101112/nha-may-che-bien-thit-bo-lon-bac-nhat-viet-nam-voi-cong-suat-10000-tan-cua-vinamilk-va-ong-lon-nhat-ban-chinh-thuc-hoat-dong.chn
 Crawl 83/1050: https://cafef.vn/du-lieu/vnm-2098150/vnm-26122024-ngay-gdkhq-tam-ung-co-tuc-dot-2-nam-2024-bang-tien-mat-500-dcp.chn
 Crawl 84/1050: https://cafef.vn/du-lieu/vnm-2097678/vnm-fn-dairy-investments-pte-ltd-chua-mua-cp.chn
 Crawl 85/1050: https://cafef.vn/du-lieu/vnm-2097685/vnm-fn-dairy-investments-pte-ltd-dang-ky-mua-20899554-cp.chn
 Crawl 86/1050: https://cafef.vn/du-lieu/vnm-2096198/vnm-thong-bao-ngay-dkcc-de-thuc-hien-quyen-nhan-tam-ung-co-tuc-dot-2-nam-2024-bang-tien.chn
 Crawl 87/1050: https://cafef.vn/du-lieu/vnm-2095427/vnm-nghi-quyet-hdqt-thong-qua-viec-tam-ung-co-tuc-bang-tien-mat-dot-2-nam-2024.chn
 Crawl 88/1050: https://cafef.vn/du-lieu/vnm-2095435/vnm-nghi-quyet-hdqt-ve-viec-thong-qua-giao-dich-voi-ben-lien-quan.chn
 Crawl 89/1050: https://cafef.vn/du-lieu/vnm-2090372/vnm-platinum-victory-pte-ltd-cdl-chua-mua-cp.chn
 Crawl 90/1050: https://cafef.vn/du-lieu/vnm-2090374/vnm-platinum-victory-pte-ltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 91/1050: https://cafef.vn/du-lieu/vnm-2084693/mcm-nghi-quyet-hdqt-ve-viec-thong-qua-giao-dich-voi-vnm.chn
 Crawl 92/1050: https://cafef.vn/du-lieu/vnm-2081346/vnm-fn-dairy-investments-pteltd-chua-mua-cp.chn
 Crawl 93/1050: https://cafef.vn/du-lieu/vnm-2081347/vnm-fn-dairy-investments-pteltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 94/1050: https://cafef.vn/du-lieu/vnm-2077981/ceo-mai-kieu-lien-ty-le-uong-sua-cua-nguoi-viet-thap-so-voi-khu-vuc-day-la-dieu-dang-lo-ngai.chn
 Crawl 95/1050: https://cafef.vn/du-lieu/vnm-2077591/nhung-cai-ten-lai-lon-nhat-san-chung-khoan-quy-32024-vinhomes-doi-lai-ngoi-vuong-mot-cai-ten-gay-bat-ngo.chn
 Crawl 96/1050: https://cafef.vn/du-lieu/vnm-2073126/vnm-platinum-victory-pte-ltd-cdl-chua-mua-cp.chn
 Crawl 97/1050: https://cafef.vn/du-lieu/vnm-2073128/vnm-platinum-victory-pte-ltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 98/1050: https://cafef.vn/du-lieu/vnm-2135317/lam-chu-san-nha-ong-pham-nhat-vuong-va-tran-dinh-long-ba-chu-2-nganh-cong-nghiep-nang-tai-mien-bac-cac-doanh-nhan-mien-nam-chiem-linh-thi-truong-ban-le.chn
 Crawl 99/1050: https://cafef.vn/du-lieu/vnm-2063878/vnm-fn-dairy-investments-pte-ltd-chua-mua-cp.chn
 Crawl 100/1050: https://cafef.vn/du-lieu/vnm-2063880/vnm-fn-dairy-investments-pte-ltd-dang-ky-mua-20899554-cp.chn
 Crawl 101/1050: https://cafef.vn/du-lieu/vnm-2059787/mcm-nghi-quyet-hdqt-thong-qua-giao-dich-voi-vnm.chn
 Crawl 102/1050: https://cafef.vn/du-lieu/vnm-2055648/vnm-platinum-victory-pte-ltd-chua-mua-cp.chn
 Crawl 103/1050: https://cafef.vn/du-lieu/vnm-2053370/vinamilk-ho-tro-gan-3-ty-dong-san-pham-dinh-duong-thiet-yeu-cho-10-tinh-thanh-anh-huong-bao-lu.chn
 Crawl 104/1050: https://cafef.vn/du-lieu/vnm-2048301/vnm-2492024-ngay-gdkhq-thanh-toan-co-tuc-dot-cuoi-nam-2023-va-tam-ung-co-tuc-dot-12024-bang-tien-mat-2450-dcp.chn
 Crawl 105/1050: https://cafef.vn/du-lieu/vnm-2049170/vnm-fn-dairy-investments-pteltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 106/1050: https://cafef.vn/du-lieu/vnm-2049173/vnm-fn-dairy-investments-pteltd-chua-mua-cp.chn
 Crawl 107/1050: https://cafef.vn/du-lieu/vnm-2045766/vnm-thong-bao-ve-ngay-dkcc-thanh-toan-co-tuc-dot-cuoi-nam-2023-va-tam-ung-co-tuc-dot-1-nam-2024-bang-tien-mat.chn
 Crawl 108/1050: https://cafef.vn/du-lieu/vnm-2043232/vnm-cbtt-chot-danh-sach-nhan-co-tuc.chn
 Crawl 109/1050: https://cafef.vn/du-lieu/vnm-2039060/lien-tuc-dang-ky-mua-co-phieu-vinamilk-roi-huy-keo-ti-phu-thai-lan-va-ca-map-singapore-dang-suy-tinh-gi.chn
 Crawl 110/1050: https://cafef.vn/du-lieu/vnm-2038660/vnm-platinum-victory-pte-ltd-chua-mua-cp.chn
 Crawl 111/1050: https://cafef.vn/du-lieu/vnm-2038661/vnm-platinum-victory-pte-ltd-dang-ky-mua-20899554-cp.chn
 Crawl 112/1050: https://cafef.vn/du-lieu/vnm-2037265/cong-ty-bat-dong-san-von-60-ty-vua-chi-2000-ty-dong-tra-co-tuc-co-dong-nha-nuoc-nhan-ve-600-ty-gap-33-lan-von-dau-tu.chn
 Crawl 113/1050: https://cafef.vn/du-lieu/vnm-2037504/vnm-giai-trinh-bien-dong-ket-qua-kinh-doanh-6-thang-dau-nam-2024-so-voi-6-thang-dau-nam-2023.chn
 Crawl 114/1050: https://cafef.vn/du-lieu/vnm-2035642/vnm-giai-trinh-chenh-lech-kqkd-q22024-so-voi-cung-ky-nam-truoc.chn
 Crawl 115/1050: https://cafef.vn/du-lieu/vnm-2031454/bao-doanh-thu-ky-luc-va-loi-nhuan-cao-nhat-11-quy-co-phieu-vinamilk-tang-lien-4-phien-lay-lai-nhung-gi-da-mat-trong-4-thang.chn
 Crawl 116/1050: https://cafef.vn/du-lieu/vnm-2030895/vnm-fn-dairy-investments-pteltd-cdl-chua-mua-cp.chn
 Crawl 117/1050: https://cafef.vn/du-lieu/vnm-2030896/vnm-fn-dairy-investments-pteltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 118/1050: https://cafef.vn/du-lieu/vnm-2082358/vnm-bao-cao-tinh-hinh-quan-tri-cong-ty-06-thang-dau-nam-2024.chn
 Crawl 119/1050: https://cafef.vn/du-lieu/vnm-2020699/vnm-platinum-victory-pte-ltd-chua-mua-cp.chn
 Crawl 120/1050: https://cafef.vn/du-lieu/vnm-2020701/vnm-platinum-victory-pte-ltd-dang-ky-mua-20899554-cp.chn
 Crawl 121/1050: https://cafef.vn/du-lieu/vnm-2014754/aeon-dien-may-xanh-tro-luc-cho-doanh-thu-xe-dap-thong-nhat-len-dinh-moi-rieng-vinamilk-tieu-thu-32000-xe-tuong-duong-14-doanh-so.chn
 Crawl 122/1050: https://cafef.vn/du-lieu/vnm-2014224/vnm-fn-dairy-investments-pteltd-cdl-chua-mua-cp.chn
 Crawl 123/1050: https://cafef.vn/du-lieu/vnm-2014226/vnm-fn-dairy-investments-pteltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 124/1050: https://cafef.vn/du-lieu/vnm-2013160/vnm-bo-nhiem-ba-huynh-thi-phuong-lan-giu-chuc-ke-toan-truong-tu-172024.chn
 Crawl 125/1050: https://cafef.vn/du-lieu/vnm-2011932/vinamilk-lan-dau-tien-thay-ke-toan-truong-sau-20-nam.chn
 Crawl 126/1050: https://cafef.vn/du-lieu/vnm-2010697/vnm-cong-ty-tnhh-mot-thanh-vien-dau-tu-scic-sic-da-mua-950000-cp.chn
 Crawl 127/1050: https://cafef.vn/du-lieu/vnm-2004561/dai-dien-vinamilk-sua-viet-nam-san-sang-tham-gia-chuoi-ban-le-toan-cau.chn
 Crawl 128/1050: https://cafef.vn/du-lieu/vnm-2002577/vnm-platinum-victory-pte-ltd-chua-mua-cp.chn
 Crawl 129/1050: https://cafef.vn/du-lieu/vnm-2002579/vnm-platinum-victory-pte-ltd-dang-ky-mua-20899554-cp.chn
 Crawl 130/1050: https://cafef.vn/du-lieu/vnm-2000819/tang-120-tu-dau-nam-von-hoa-masan-consumer-vuot-qua-vinamilk-tro-thanh-cong-ty-lon-nhat-nganh-thuc-pham-do-uong-tren-san-chung-khoan.chn
 Crawl 131/1050: https://cafef.vn/du-lieu/vnm-1998784/vnm-cong-ty-tnhh-mot-thanh-vien-dau-tu-scic-dang-ky-mua-950000-cp.chn
 Crawl 132/1050: https://cafef.vn/du-lieu/vnm-1997084/vnm-hdqt-thong-qua-nghi-quyet-ve-viec-lua-chon-don-vi-kiem-toan-doc-lap.chn
 Crawl 133/1050: https://cafef.vn/du-lieu/vnm-1997098/vnm-fn-dairy-investments-pteltd-cdl-chua-mua-cp.chn
 Crawl 134/1050: https://cafef.vn/du-lieu/vnm-1997099/vnm-fn-dairy-investments-pteltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 135/1050: https://cafef.vn/du-lieu/vnm-1983696/vinamilk-thi-truong-nuoc-ngoai-tiep-tuc-dan-dat-tang-truong-doanh-thu-3-thang-dau-nam.chn
 Crawl 136/1050: https://cafef.vn/du-lieu/vnm-1985695/vnm-nghi-quyet-va-bien-ban-hop-dhdcd-thuong-nien-nam-2024.chn
 Crawl 137/1050: https://cafef.vn/du-lieu/vnm-1996584/vnm-bo-nhiem-ong-le-duc-anh-giu-chuc-thu-ky-cong-ty-tu-152024.chn
 Crawl 138/1050: https://cafef.vn/du-lieu/vnm-2010266/vnm-giai-trinh-chenh-lech-loi-nhuan-sau-thue-quy-12024-so-voi-quy-12023.chn
 Crawl 139/1050: https://cafef.vn/du-lieu/vnm-1982902/dhdcd-vinamilk-quy-12024-loi-nhuan-tang-truong-16.chn
 Crawl 140/1050: https://cafef.vn/du-lieu/vnm-1987509/vnm-platinum-victory-pte-ltd-chua-mua-cp.chn
 Crawl 141/1050: https://cafef.vn/du-lieu/vnm-1987513/vnm-platinum-victory-pte-ltd-dang-ky-mua-20899554-cp.chn
 Crawl 142/1050: https://cafef.vn/du-lieu/vnm-1982326/vinamilk-co-them-1-nha-may-dat-chung-nhan-trung-hoa-carbon-day-manh-xanh-hoa-san-xuat.chn
 Crawl 143/1050: https://cafef.vn/du-lieu/vnm-1980504/det-may-tcm-fpt-thaco-vinamilk-nutifood-tich-cuc-chi-hang-trieu-usd-thau-tom-doi-tac-ngoai.chn
 Crawl 144/1050: https://cafef.vn/du-lieu/vnm-1979304/tang-truong-tai-cac-thi-truong-chu-luc-thuc-day-doanh-so-xuat-khau-cua-vinamilk.chn
 Crawl 145/1050: https://cafef.vn/du-lieu/vnm-1980418/vnm-fn-dairy-investments-pteltd-cdl-chua-mua-cp.chn
 Crawl 146/1050: https://cafef.vn/du-lieu/vnm-1980420/vnm-fn-dairy-investments-pteltd-cdl-dang-ky-mua-20899554-cp.chn
 Crawl 147/1050: https://cafef.vn/du-lieu/vnm-1971307/vinamilk-dat-muc-tieu-pha-ky-luc-doanh-thu-du-chi-hon-8000-ty-co-tuc-cho-nam-2024.chn
 Crawl 148/1050: https://cafef.vn/du-lieu/vnm-1971477/vnm-cbtt-duong-dan-tai-lieu-hop-dhdcd-thuong-nien-nam-2024.chn
 Crawl 149/1050: https://cafef.vn/du-lieu/vnm-1970829/vnm-cong-ty-tnhh-mot-thanh-vien-dau-tu-scic-sis-da-mua-200000-cp.chn
 Crawl 150/1050: https://cafef.vn/du-lieu/vnm-1964344/khong-ho-danh-la-vua-quang-cao-tieu-3-tyngay-ty-le-choi-cho-vi-tri-marketing-tai-vinamilk-la-1150-kho-hon-dai-hoc-top-dau-viet-nam.chn
 Crawl 151/1050: https://cafef.vn/du-lieu/vnm-1962837/bien-dong-danh-sach-cac-ca-map-nam-gan-80-von-vinamilk-dragon-capital-vanguard-cac-quy-etf-mua-manh-hsbc-prudential-citigoup-jpmorgan-ban-ra-ca-chuc-trieu-co-phieu.chn
 Crawl 152/1050: https://cafef.vn/du-lieu/vnm-1963536/vnm-platinum-victory-pte-ltd-chua-mua-cp.chn
 Crawl 153/1050: https://cafef.vn/du-lieu/vnm-1963537/vnm-platinum-victory-pte-ltd-dang-ky-mua-20899554-cp.chn
 Crawl 154/1050: https://cafef.vn/du-lieu/vnm-1962330/vnm-fn-dairy-investments-pteltd-cdl-chua-mua-cp.chn

Tiếp tục crawl các bài báo

In [ ]:
pip install selenium

Collecting selenium
  Downloading selenium-4.36.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: urllib3<3.0,>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (2.5.0)
Collecting trio<1.0,>=0.30.0 (from selenium)
  Downloading trio-0.31.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: certifi>=2025.6.15 in /usr/local/lib/python3.12/dist-packages (from selenium) (2025.10.5)
Requirement already satisfied: typing_extensions<5.0,>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (4.15.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.30.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.30.0->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.30.0->selenium) (3.10)
Collecting outcome (from trio<1.0,>=0.30.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.30.0->selenium) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.5.0->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.36.0-py3-none-any.whl (9.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 66.5 MB/s eta 0:00:00
Downloading trio-0.31.0-py3-none-any.whl (512 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 512.7/512.7 kB 35.1 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, outcome, trio, trio-websocket, selenium
Successfully installed outcome-1.3.0.post0 selenium-4.36.0 trio-0.31.0 trio-websocket-0.12.2 wsproto-1.2.0

In [ ]:
import pandas as pd
import time
import os
from datetime import datetime
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException

# --- Khởi tạo Edge driver ---
def init_driver():
    options = webdriver.EdgeOptions()
    options.add_argument("--headless")
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    driver = webdriver.Edge(options=options)
    return driver


# --- Hàm crawl nội dung 1 bài báo ---
def crawl_article_content(url):
    driver = init_driver()
    try:
        driver.get(url)
        time.sleep(2)  # chờ load JS

        content_texts = []

        # Tìm phần detail-content
        try:
            detail = driver.find_element(
                By.XPATH, '//div[contains(@class, "detail-content")]'
            )
        except NoSuchElementException:
            detail = None

        if detail:
            # Lấy sapo nếu có
            try:
                sapo = detail.find_element(By.XPATH, './/h2').text.strip()
                if sapo:
                    content_texts.append(sapo)
            except NoSuchElementException:
                pass

            # Lấy tất cả các đoạn <p>
            paras = detail.find_elements(By.XPATH, './/p')
            for p in paras:
                txt = p.text.strip()
                if txt and not txt.startswith(">>>"):  # bỏ dòng quảng cáo
                    content_texts.append(txt)

        # Nếu không tìm thấy detail-content thì fallback sang mainContent
        if not content_texts:
            try:
                paras2 = driver.find_elements(By.XPATH, '//*[@id="mainContent"]//p')
                for p in paras2:
                    txt = p.text.strip()
                    if txt:
                        content_texts.append(txt)
            except NoSuchElementException:
                pass

        return "\n".join(content_texts) if content_texts else None

    except Exception as e:
        print(f" Lỗi khi crawl {url}: {e}")
        return None
    finally:
        driver.quit()


# --- File CSV đầu vào ---
file_path = "/content/drive/MyDrive/cafef_news/cafef_gas.csv"

if not os.path.exists(file_path):
    print(f" Error: File not found at {file_path}")
else:
    df = pd.read_csv(file_path)

    # Nếu chưa có cột "Nội dung" thì thêm
    if "Nội dung" not in df.columns:
        df["Nội dung"] = None

    # Chuẩn hóa thời gian
    df["Thời gian"] = pd.to_datetime(
        df["Thời gian"], errors="coerce"
    )


    # Lọc khoảng thời gian
    start_date = datetime(2025, 1, 1)
    end_date = datetime(2025, 10, 1)
    mask = (df["Thời gian"] >= start_date) & (df["Thời gian"] <= end_date)
    df_target = df[mask]
    print(f" Có {len(df_target)} bài trong khoảng từ {start_date.date()} đến {end_date.date()}")

    # Crawl nội dung
    for i, row in df_target.iterrows():
        if pd.isna(row["Nội dung"]) or not row["Nội dung"]:
            url = row["URL"]
            print(f" Crawl {i+1}/{len(df_target)}: {url}")
            content = crawl_article_content(url)
            df.at[i, "Nội dung"] = content

            # Lưu tạm để tránh mất dữ liệu
            df.to_csv(file_path, index=False, encoding="utf-8-sig")

    print(f"\n Đã cập nhật nội dung vào file: {file_path}")

 Có 57 bài trong khoảng từ 2025-01-01 đến 2025-10-01
 Crawl 1/57: https://cafef.vn/pv-gas-duoc-chap-thuan-dau-tu-du-an-kho-lng-bac-trung-bo-26700-ty-dong-tai-ha-tinh-18825092213391668.chn
 Crawl 2/57: https://cafef.vn/du-lieu/GAS-2300212/gas-nghi-quyet-hdqt-vv-tang-von-dieu-le-sua-doi-dieu-le-thay-doi-noi-dung-dang-ky-doanh-nghiep.chn
 Crawl 3/57: https://cafef.vn/du-lieu/GAS-2296600/pvg-nghi-quyet-hdqt-thong-qua-noi-dung-chinh-hop-dong-thue-vo-chai-lpg.chn
 Crawl 4/57: https://cafef.vn/du-lieu/GAS-2293836/pgs-nghi-quyet-hdqt-tham-gia-dau-gia-lo-chai-cu-lpg-rong-cua-pvgas.chn
 Crawl 5/57: https://cafef.vn/du-lieu/GAS-2292168/gas-thong-bao-thay-doi-so-luong-co-phieu-co-quyen-bieu-quyet-va-bao-cao-ket-qua-phat-hanh-co-phieu-de-tang-von-co-phan-tu-nvcsh.chn
 Crawl 6/57: https://cafef.vn/nhung-doanh-nghiep-co-nhan-vien-kiem-tien-khoe-nhat-san-chung-khoan-binh-quan-moi-nguoi-mang-ve-35-ty-doanh-thuthang-bat-ngo-voi-top-1-18825090608323733.chn
 Crawl 7/57: https://cafef.vn/du-lieu/GAS-2289739/gas-thong-bao-giay-xac-nhan-thay-doi-noi-dung-dkdn.chn
 Crawl 8/57: https://cafef.vn/duong-ong-dan-khi-370-km-dai-nhat-viet-nam-van-chuyen-hon-110-ty-m-khi-dn-nao-dung-sau-188250827082410492.chn
 Crawl 9/57: https://cafef.vn/du-lieu/GAS-2280246/psi-nghi-quyet-hdqt-thong-qua-hop-dong-voi-pvgas.chn
 Crawl 10/57: https://cafef.vn/du-lieu/GAS-2281664/gas-giay-chung-nhan-dang-ky-doanh-nghiep-thay-doi-lan-thu-22.chn
 Crawl 11/57: https://cafef.vn/nhung-dai-gia-dem-tien-mat-di-tra-het-no-van-con-hon-chuc-nghin-ty-188250819071520593.chn
 Crawl 12/57: https://cafef.vn/du-lieu/GAS-2263659/gas-2882025-ngay-gdkhq-tra-co-tuc-nam-2024-bang-tien-2100-dcp-thuong-cp-ty-le-1003.chn
 Crawl 13/57: https://cafef.vn/20-doanh-nghiep-niem-yet-lai-lon-nhat-6t2025-60-la-ngan-hang-15-la-bat-dong-san-chi-co-1-dn-san-xuat-188250802085619235.chn
 Crawl 14/57: https://cafef.vn/du-lieu/GAS-2292830/gas-bao-cao-tinh-hinh-quan-tri-cong-ty-06-thang-dau-nam-2025.chn
 Crawl 15/57: https://cafef.vn/du-lieu/GAS-2271861/gas-thong-bao-so-29-va-30-ngay-28072025.chn
 Crawl 16/57: https://cafef.vn/du-lieu/GAS-2256830/gas-nghi-quyet-hdqt-vv-tra-co-tuc-nam-2024.chn
 Crawl 17/57: https://cafef.vn/du-an-trong-diem-lo-b-o-mon-su-tu-trang-2b-dang-tao-ra-khoi-luong-cong-viec-khong-lo-len-den-hang-ty-usd-cho-pvd-pvs-18825070410061419.chn
 Crawl 18/57: https://cafef.vn/du-lieu/GAS-2239405/gas-nghi-quyet-hdqt-so-68-va-ky-hop-dong-kiem-toan-bctc.chn
 Crawl 19/57: https://cafef.vn/cuoc-dua-von-hoa-25-nam-mot-cong-ty-thuy-dien-tung-giu-ngoi-vua-truoc-khi-nhung-ga-khong-lo-fpt-vinamilk-vietcombank-tran-len-san-188250702070405395.chn
 Crawl 20/57: https://cafef.vn/du-lieu/GAS-2236099/gas-nghi-quyet-hdqt-so-66-ngay-30062025.chn
 Crawl 21/57: https://cafef.vn/gia-dau-tang-nong-sau-dien-bien-moi-tai-trung-dong-co-phieu-dau-khi-dong-loat-boc-dau-188250623093139531.chn
 Crawl 22/57: https://cafef.vn/du-bao-nganh-dau-khi-q22025-ca-nganh-bao-lai-lon-vi-sao-hai-ong-lon-petrolimex-va-bsr-lai-sut-giam-toi-35-va-91-188250622224756695.chn
 Crawl 23/57: https://cafef.vn/du-lieu/GAS-2224271/gas-dinh-chinh-bctc-hop-nhat-quy-12025.chn
 Crawl 24/57: https://cafef.vn/co-phieu-dau-khi-nong-bong-tay-dong-loat-tang-1015-sau-2-phien-co-ma-len-cao-nhat-tu-dau-nam-188250616140949851.chn
 Crawl 25/57: https://cafef.vn/gia-dau-tang-vot-co-phieu-dau-khi-dong-loat-noi-song-dieu-gi-dang-dien-ra-188250613094243719.chn
 Crawl 26/57: https://cafef.vn/cong-ty-dien-2000-ty-vua-thanh-lap-cua-ong-pham-nhat-vuong-cung-loat-dn-dau-khi-nang-luong-tai-tao-duoc-du-bao-huong-loi-tu-quy-hoach-dien-viii-sua-doi-188250607074758222.chn
 Crawl 27/57: https://cafef.vn/du-lieu/GAS-2213058/gas-bo-nhiem-ong-nguyen-minh-tuan-giu-chuc-pho-tong-giam-doc-tu-262025.chn
 Crawl 28/57: https://cafef.vn/du-lieu/GAS-2212168/gas-thong-bao-thay-doi-nhan-su-thanh-vien-hdqt-va-bks.chn
 Crawl 29/57: https://cafef.vn/du-lieu/GAS-2212176/gas-nghi-quyet-va-bien-ban-dhdcd-thuong-nien-nam-2025.chn
 Crawl 30/57: https://cafef.vn/cong-ty-gia-tri-hon-152000-ty-dong-lon-thu-12-ttck-viet-noi-gi-truoc-nguy-co-bi-huy-niem-yet-co-phieu-188250531084655444.chn
 Crawl 31/57: https://cafef.vn/du-lieu/gas-2208480/gas-nghi-quyet-hdqt-vv-chap-thuan-noi-dung-chinh-cua-thoa-thuan-sua-doi-gspa-061.chn
 Crawl 32/57: https://cafef.vn/du-lieu/gas-2205175/gas-nghi-quyet-hdqt-chap-thuan-noi-dung-chinh-cua-hop-dong-mua-ban-khi-lo-1211.chn
 Crawl 33/57: https://cafef.vn/du-lieu/gas-2201210/pvg-nghi-quyet-hdqt-thong-qua-cac-noi-dung-chinh-cua-hop-dong-thue-vo-chai-lpg.chn
 Crawl 34/57: https://cafef.vn/du-lieu/gas-2194407/pvn-pv-gas-vnvc-vietnam-airlines-ky-loat-hop-tac-cung-cac-tap-doan-nga-truoc-su-chung-kien-cua-tong-bi-thu-to-lam-va-tong-thong-vladimir-putin.chn
 Crawl 35/57: https://cafef.vn/du-lieu/gas-2201301/gas-thu-moi-tham-du-dhdcd-thuong-nien-nam-2025.chn
 Crawl 36/57: https://cafef.vn/du-lieu/gas-2183479/gas-nghi-quyet-hdqt-thong-qua-cac-noi-dung-de-phuc-vu-kinh-doanh-nam-2025.chn
 Crawl 37/57: https://cafef.vn/du-lieu/gas-2173415/gas-quyet-dinh-ve-viec-thanh-lap-chi-nhanh-logistics.chn
 Crawl 38/57: https://cafef.vn/du-lieu/gas-2171347/no-luc-thu-hep-tham-hut-thuong-mai-my-viet-loat-don-hang-ty-do-cua-vietnam-airlines-vietjet-pv-gas.chn
 Crawl 39/57: https://cafef.vn/du-lieu/gas-2171076/mot-tau-vang-long-se-duoc-dua-ve-kho-cang-300-trieu-usd-thi-vai-trong-thang-nay.chn
 Crawl 40/57: https://cafef.vn/du-lieu/gas-2181262/gas-2842025-ngay-gdkhq-tham-du-dhdcd-thuong-nien-nam-2025.chn
 Crawl 41/57: https://cafef.vn/du-lieu/gas-2168810/gas-thong-bao-ngay-dkcc-de-thuc-hien-quyen-tham-du-dhcd-thuong-nien-nam-2025.chn
 Crawl 42/57: https://cafef.vn/du-lieu/gas-2167412/gas-nghi-quyet-hdqt-ve-viec-to-chuc-hop-dhdcd-thuong-nien-2025.chn
 Crawl 43/57: https://cafef.vn/du-lieu/gas-2154055/gas-nhac-nho-cham-cong-bo-thong-tin-nghi-quyet-hdqt.chn
 Crawl 44/57: https://cafef.vn/du-lieu/gas-2144751/gas-bo-nhiem-ong-nguyen-anh-tuan-giu-chuc-ke-toan-truong-tu-532025.chn
 Crawl 45/57: https://cafef.vn/du-lieu/gas-2144752/gas-quyet-dinh-ve-viec-bo-nhiem-ke-toan-truong.chn
 Crawl 46/57: https://cafef.vn/du-lieu/gas-2142689/gas-nghi-quyet-hdqt-chap-thuan-noi-dung-chinh-cua-thoa-thuan-thanh-quyet-toan-tien-mua-ban-khi-nam-2024-voi-pvfcco.chn
 Crawl 47/57: https://cafef.vn/du-lieu/gas-2139440/gas-nghi-quyet-hdqt-so-16-ngay-25022025.chn
 Crawl 48/57: https://cafef.vn/du-lieu/gas-2136987/gas-bo-nhiem-lai-ong-huynh-quang-hai-giu-chuc-pho-tong-giam-doc.chn
 Crawl 49/57: https://cafef.vn/du-lieu/gas-2134852/gas-bo-nhiem-lai-ong-huynh-quang-hai-giu-chuc-pho-tong-giam-doc.chn
 Crawl 50/57: https://cafef.vn/du-lieu/gas-2130526/gas-cbtt-thanh-lap-cong-ty-pvgas-international.chn
 Crawl 51/57: https://cafef.vn/du-lieu/gas-2135892/top-50-loi-nhuan-2024-van-la-cuoc-ap-dao-cua-ngan-hang-va-bds-bsr-kbc-hag-nvl-bien-mat-trong-khi-2-cong-ty-ho-gelex-troi-day.chn
 Crawl 52/57: https://cafef.vn/du-lieu/gas-2122564/pv-gas-dat-doanh-thu-cao-nhat-lich-su-moi-ngay-thu-ve-khoang-4-ty-dong-lai-tien-gui-ngan-hang.chn
 Crawl 53/57: https://cafef.vn/du-lieu/gas-2134891/gas-bao-cao-tinh-hinh-quan-tri-cong-ty-nam-2024.chn
 Crawl 54/57: https://cafef.vn/du-lieu/gas-2120465/gas-nghi-quyet-hdqt-so-06-07-ngay-22012024.chn
 Crawl 55/57: https://cafef.vn/du-lieu/gas-2135310/masan-chi-1600-ty-mua-5-tang-lau-quan-1-cua-techcombank-lam-phi-thuyen-vu-tru-acv-va-vietjet-lap-quan-hang-khong-tai-tan-binh.chn
 Crawl 56/57: https://cafef.vn/du-lieu/gas-2116604/gas-giay-chung-nhan-dang-ky-doanh-nghiep-thay-doi-lan-thu-21.chn
 Crawl 57/57: https://cafef.vn/du-lieu/gas-2111748/xuat-hien-nhung-cong-ty-bao-lai-nghin-ty-dau-tien-2-dai-gia-nha-nuoc-hoi-sinh-ngat-mach-thua-lo.chn

 Đã cập nhật nội dung vào file: /content/drive/MyDrive/cafef_news/cafef_gas.csv

In [ ]:
import pandas as pd
import re
from collections import Counter
import string
import os

def analyze_article_data(file_path):
    """
    Phân tích thống kê cơ bản cho các trường 'Nội dung' và 'Tiêu đề'
    của các bài báo trong một file CSV.

    Args:
        file_path (str): Đường dẫn đến file CSV (ví dụ: 'cafef_hpg.csv').
    """
    # 1. Đọc dữ liệu
    try:
        df = pd.read_csv(file_path)
    except FileNotFoundError:
        print(f"Lỗi: Không tìm thấy file tại đường dẫn: {file_path}")
        return
    except Exception as e:
        print(f"Lỗi khi đọc file {file_path}: {e}")
        return

    print(f"=====================================================")
    print(f"| BẮT ĐẦU PHÂN TÍCH DỮ LIỆU TỪ FILE: {os.path.basename(file_path)} |")
    print(f"=====================================================\n")

    # 2. Xử lý trường Nội dung

    # 2.1. Số lượng bài báo chưa có nội dung
    # Kiểm tra các giá trị null/None và chuỗi rỗng sau khi loại bỏ khoảng trắng
    df['Nội dung'] = df['Nội dung'].astype(str).str.strip()
    articles_missing_content = df[df['Nội dung'].isin(['', 'None', 'nan'])].shape[0]

    # Lọc ra các bài báo có nội dung để phân tích thống kê
    df_content = df[~df['Nội dung'].isin(['', 'None', 'nan'])].copy()

    # 2.2. Thống kê độ dài Nội dung (theo số từ)
    if not df_content.empty:
        # Hàm đếm số từ: loại bỏ dấu câu và đếm
        def count_words(text):
            if pd.isna(text) or text.strip() == '':
                return 0
            # Thay thế các ký tự không phải chữ cái/số/khoảng trắng bằng khoảng trắng
            text = re.sub(r'[^\w\s]', ' ', text)
            return len(text.split())

        df_content['Word Count'] = df_content['Nội dung'].apply(count_words)

        avg_words = df_content['Word Count'].mean()
        max_words = df_content['Word Count'].max()
        min_words = df_content['Word Count'].min()

        print(f"--- THỐNG KÊ TRƯỜNG 'NỘI DUNG' ---")
        print(f"Tổng số bài báo: {len(df)}")
        print(f"Số lượng bài báo không có nội dung (None/Rỗng): {articles_missing_content}")
        print(f"Số lượng bài báo có nội dung để phân tích: {len(df_content)}")
        print(f"Trung bình số từ một bài báo: {avg_words:.2f} từ")
        print(f"Bài báo dài nhất: {max_words} từ")
        print(f"Bài báo ngắn nhất: {min_words} từ")

        # 2.3. Thống kê từ vựng phổ biến (Top 10)
        all_words = []
        for content in df_content['Nội dung']:
            # Chuyển về chữ thường, loại bỏ dấu câu, tách từ
            text = content.lower()
            text = re.sub(r'[^\w\s]', '', text)
            all_words.extend(text.split())

        word_counts = Counter(all_words)
        # Lọc bỏ các từ dừng (stop-words) tiếng Việt cơ bản có thể được thêm vào đây,
        # nhưng ở đây ta chỉ lọc các ký tự đơn hoặc số.

        # Lọc các từ chỉ có 1 ký tự (thường là lỗi hoặc ký tự không quan trọng)
        top_words = {word: count for word, count in word_counts.most_common(50) if len(word) > 1}
        top_10 = dict(list(top_words.items())[:10])

        print("\nTop 10 từ xuất hiện nhiều nhất trong Nội dung:")
        for word, count in top_10.items():
            print(f"- {word}: {count} lần")
    else:
        print(f"Không có nội dung bài báo nào để phân tích thống kê độ dài và từ vựng.")

    # 3. Xử lý trường Tiêu đề

    # Lọc ra các tiêu đề không rỗng
    df['Tiêu đề'] = df['Tiêu đề'].astype(str).str.strip()
    df_title = df[~df['Tiêu đề'].isin(['', 'None', 'nan'])].copy()

    if not df_title.empty:
        # Thống kê độ dài Tiêu đề (theo số từ)
        df_title['Title Word Count'] = df_title['Tiêu đề'].apply(count_words) # Sử dụng lại hàm count_words

        avg_title_words = df_title['Title Word Count'].mean()
        max_title_words = df_title['Title Word Count'].max()
        min_title_words = df_title['Title Word Count'].min()

        # Thống kê độ dài Tiêu đề (theo số ký tự)
        df_title['Title Char Count'] = df_title['Tiêu đề'].apply(len)
        max_title_chars = df_title['Title Char Count'].max()
        min_title_chars = df_title['Title Char Count'].min()
        avg_title_chars = df_title['Title Char Count'].mean()

        print(f"\n--- THỐNG KÊ TRƯỜNG 'TIÊU ĐỀ' ---")
        print(f"Trung bình số từ một tiêu đề: {avg_title_words:.2f} từ")
        print(f"Tiêu đề dài nhất: {max_title_words} từ ({max_title_chars} ký tự)")
        print(f"Tiêu đề ngắn nhất: {min_title_words} từ ({min_title_chars} ký tự)")
        print(f"Trung bình số ký tự một tiêu đề: {avg_title_chars:.2f} ký tự")

        # Thống kê từ vựng phổ biến trong Tiêu đề (Top 5)
        all_title_words = []
        for title in df_title['Tiêu đề']:
            text = title.lower()
            text = re.sub(r'[^\w\s]', '', text)
            all_title_words.extend(text.split())

        title_word_counts = Counter(all_title_words)
        top_5_title_words = {word: count for word, count in title_word_counts.most_common(10) if len(word) > 1}
        top_5 = dict(list(top_5_title_words.items())[:5])

        print("\nTop 5 từ xuất hiện nhiều nhất trong Tiêu đề:")
        for word, count in top_5.items():
            print(f"- {word}: {count} lần")
    else:
        print(f"\nKhông có tiêu đề bài báo nào để phân tích thống kê.")

    print(f"\n=====================================================")
    print(f"| KẾT THÚC PHÂN TÍCH FILE: {os.path.basename(file_path)} |")
    print(f"=====================================================\n")

# --- VÍ DỤ MINH HỌA CÁCH SỬ DỤNG ---

# Giả định các file của bạn nằm trong thư mục 'cafef_new'
# Tạo một file giả định để test nếu bạn chưa có data thực
# VÍ DỤ: Tạo một file CSV giả định để chạy code
# stock_data = {
#     'Tiêu đề': ['Tin mới HPG: Lợi nhuận kỷ lục', 'Tác động của VCB', 'VCB tăng trưởng mạnh mẽ.', 'Nội dung None'],
#     'Nội dung': ['Hòa Phát (HPG) báo cáo lợi nhuận ròng quý 3/2025 đạt 10.000 tỷ đồng, vượt xa kỳ vọng của thị trường. Đây là kỷ lục mới của ngành thép.',
#                  'Việc Ngân hàng Vietcombank (VCB) cắt giảm lãi suất cho vay đã có tác động lớn đến thị trường bất động sản trong nước.',
#                  'Cổ phiếu VCB đang cho thấy tiềm năng tăng trưởng vượt trội nhờ vào chất lượng tài sản tốt và chiến lược mở rộng tín dụng.',
#                  None]
# }
# df_test_hpg = pd.DataFrame(stock_data)
# os.makedirs('cafef_new', exist_ok=True)
# df_test_hpg.to_csv('cafef_new/cafef_HPG.csv', index=False)
# df_test_vcb = df_test_hpg.copy()
# df_test_vcb.to_csv('cafef_new/cafef_VCB.csv', index=False)


# Danh sách các file bạn muốn phân tích
file_list = [
    '/content/drive/MyDrive/cafef_news/cafef_hpg.csv'
    # 'cafef_new/cafef_VCB.csv',
    # 'cafef_new/cafef_TCS.csv' # File này có thể không tồn tại trong ví dụ của tôi
]

# Chạy phân tích cho từng file
for f in file_list:
    analyze_article_data(f)

=====================================================
| BẮT ĐẦU PHÂN TÍCH DỮ LIỆU TỪ FILE: cafef_hpg.csv |
=====================================================

--- THỐNG KÊ TRƯỜNG 'NỘI DUNG' ---
Tổng số bài báo: 750
Số lượng bài báo không có nội dung (None/Rỗng): 330
Số lượng bài báo có nội dung để phân tích: 420
Trung bình số từ một bài báo: 776.49 từ
Bài báo dài nhất: 2883 từ
Bài báo ngắn nhất: 129 từ

Top 10 từ xuất hiện nhiều nhất trong Nội dung:
- thép: 4586 lần
- trong: 4336 lần
- với: 3949 lần
- và: 3795 lần
- tỷ: 3770 lần
- năm: 3679 lần
- của: 3613 lần
- phát: 3378 lần
- tăng: 2990 lần
- đồng: 2935 lần

--- THỐNG KÊ TRƯỜNG 'TIÊU ĐỀ' ---
Trung bình số từ một tiêu đề: 19.49 từ
Tiêu đề dài nhất: 38 từ (176 ký tự)
Tiêu đề ngắn nhất: 6 từ (27 ký tự)
Trung bình số ký tự một tiêu đề: 86.23 ký tự

Top 5 từ xuất hiện nhiều nhất trong Tiêu đề:
- phát: 366 lần
- hpg: 286 lần
- hòa: 270 lần
- tỷ: 262 lần
- cổ: 227 lần

=====================================================
| KẾT THÚC PHÂN TÍCH FILE: cafef_hpg.csv |
=====================================================

In [ ]:
import pandas as pd
import time
import os
from datetime import datetime
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException

# ========================================
# 1️⃣ Khởi tạo Edge driver (chạy ngầm)
# ========================================
def init_driver():
    options = webdriver.EdgeOptions()
    options.add_argument("--headless")
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    driver = webdriver.Edge(options=options)
    return driver


# ========================================
# 2️⃣ Hàm crawl nội dung 1 bài báo
# ========================================
def crawl_article_content(url):
    driver = init_driver()
    try:
        driver.get(url)
        time.sleep(2)  # chờ load JS

        content_texts = []

        # --- Tìm phần detail-content ---
        try:
            detail = driver.find_element(
                By.XPATH, '//div[contains(@class, "detail-content")]'
            )
        except NoSuchElementException:
            detail = None

        if detail:
            # Lấy sapo (nếu có)
            try:
                sapo = detail.find_element(By.XPATH, ".//h2").text.strip()
                if sapo:
                    content_texts.append(sapo)
            except NoSuchElementException:
                pass

            # Lấy các đoạn <p>
            for p in detail.find_elements(By.XPATH, ".//p"):
                txt = p.text.strip()
                if txt and not txt.startswith(">>>"):
                    content_texts.append(txt)

        # --- Fallback: tìm trong mainContent ---
        if not content_texts:
            try:
                paras2 = driver.find_elements(By.XPATH, '//*[@id="mainContent"]//p')
                for p in paras2:
                    txt = p.text.strip()
                    if txt:
                        content_texts.append(txt)
            except NoSuchElementException:
                pass

        return "\n".join(content_texts) if content_texts else None

    except Exception as e:
        print(f"Lỗi khi crawl {url}: {e}")
        return None
    finally:
        driver.quit()


# ========================================
# 3️⃣ Đọc file CSV & xử lý
# ========================================
file_path = "/content/drive/MyDrive/cafef_news/cafef_msn.csv"

if not os.path.exists(file_path):
    print(f"❌ Không tìm thấy file: {file_path}")
else:
    df = pd.read_csv(file_path)

    # Thêm cột "Nội dung" nếu chưa có
    if "Nội dung" not in df.columns:
        df["Nội dung"] = None

    # Chuẩn hóa cột Thời gian
    df["Thời gian"] = pd.to_datetime(df["Thời gian"], errors="coerce")

    # Khoảng thời gian lọc
    start_date = datetime(2020, 1, 1)
    end_date = datetime(2022, 1, 1)

    count = 0

    # --- Lọc trước các bài nằm trong khoảng thời gian ---
    mask_time = df["Thời gian"].between(start_date, end_date, inclusive="both")
    df_filtered = df[mask_time]

    print(f"Tổng số bài trong khoảng {start_date.date()} → {end_date.date()}: {len(df_filtered)}")

    # --- Chỉ xử lý các bài có nội dung trống ---
    for i in df_filtered.index:
        if pd.isna(df.at[i, "Nội dung"]) or not str(df.at[i, "Nội dung"]).strip():
            url = df.at[i, "URL"]
            print(f"📰 Crawl bài {i+1}/{len(df)}: {url}")

            content = crawl_article_content(url)
            if content:
                df.at[i, "Nội dung"] = content
                count += 1

                # Cập nhật ngay sau mỗi lần crawl thành công
                df.to_csv(file_path, index=False, encoding="utf-8-sig")
                print(f"✅ Đã cập nhật bài {i+1} vào file CSV.\n")
            else:
                print(f"⚠️ Không lấy được nội dung: {url}\n")

    print(f"🎯 Hoàn tất! Đã crawl thêm {count} bài trong khoảng thời gian lọc.")
    print(f"📁 File đã cập nhật: {file_path}")

Tổng số bài trong khoảng 2020-01-01 → 2022-01-01: 427
📰 Crawl bài 625/1050: https://cafef.vn/du-lieu/msn-522305/msn-nghi-quyet-hdqt-so-642-ngay-30122021.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-522305/msn-nghi-quyet-hdqt-so-642-ngay-30122021.chn

📰 Crawl bài 626/1050: https://cafef.vn/du-lieu/msn-523814/msn-thong-bao-cua-hnx-ve-ngay-giao-dich-dau-tien-cua-trai-phieu-chuyen-niem-yet.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-523814/msn-thong-bao-cua-hnx-ve-ngay-giao-dich-dau-tien-cua-trai-phieu-chuyen-niem-yet.chn

📰 Crawl bài 627/1050: https://cafef.vn/du-lieu/msn-524057/msn12001-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-524057/msn12001-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn

📰 Crawl bài 628/1050: https://cafef.vn/du-lieu/msn-524060/msn12002-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-524060/msn12002-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn

📰 Crawl bài 629/1050: https://cafef.vn/du-lieu/msn-524513/msn12003-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-524513/msn12003-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn

📰 Crawl bài 630/1050: https://cafef.vn/du-lieu/msn-524516/msn11906-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-524516/msn11906-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn

📰 Crawl bài 631/1050: https://cafef.vn/du-lieu/msn-524519/msn12005-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-524519/msn12005-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn

📰 Crawl bài 633/1050: https://cafef.vn/du-lieu/msn-525593/msn-link-cong-bo-tai-lieu-lay-y-kien-co-dong-bang-van-ban.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-525593/msn-link-cong-bo-tai-lieu-lay-y-kien-co-dong-bang-van-ban.chn

📰 Crawl bài 634/1050: https://cafef.vn/du-lieu/msn-526202/hnx-ngay-31122021-giao-dich-dau-tien-cua-trai-phieu-chuyen-niem-yet-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-526202/hnx-ngay-31122021-giao-dich-dau-tien-cua-trai-phieu-chuyen-niem-yet-ctcp-tap-doan-masan.chn

📰 Crawl bài 635/1050: https://cafef.vn/du-lieu/msn-1273525/msn-niem-yet-cac-trai-phieu-phat-hanh-ra-cong-chung-tren-hnx.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1273525/msn-niem-yet-cac-trai-phieu-phat-hanh-ra-cong-chung-tren-hnx.chn

📰 Crawl bài 636/1050: https://cafef.vn/du-lieu/msn-1274950/msn-nghi-quyet-hdqt-vv-thay-doi-giam-doc-tai-chinh-ke-toan-truong-va-thong-cao-bao-chi.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1274950/msn-nghi-quyet-hdqt-vv-thay-doi-giam-doc-tai-chinh-ke-toan-truong-va-thong-cao-bao-chi.chn

📰 Crawl bài 637/1050: https://cafef.vn/du-lieu/msn-1276054/msn-nghi-quyet-hdqt-vv-lien-quan-den-giao-dich-ctcp-crownx.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1276054/msn-nghi-quyet-hdqt-vv-lien-quan-den-giao-dich-ctcp-crownx.chn

📰 Crawl bài 638/1050: https://cafef.vn/du-lieu/msn-1280239/msn-chuyen-niem-yet-trai-phieu.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1280239/msn-chuyen-niem-yet-trai-phieu.chn

📰 Crawl bài 639/1050: https://cafef.vn/du-lieu/msn-1281379/msn120010-ngay-24122021-giao-dich-dau-tien-5000000-trai-phieu-niem-yet.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1281379/msn120010-ngay-24122021-giao-dich-dau-tien-5000000-trai-phieu-niem-yet.chn

📰 Crawl bài 640/1050: https://cafef.vn/du-lieu/msn-1281625/msn120007-ngay-24122021-giao-dich-dau-tien-1000000-trai-phieu-niem-yet.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1281625/msn120007-ngay-24122021-giao-dich-dau-tien-1000000-trai-phieu-niem-yet.chn

📰 Crawl bài 641/1050: https://cafef.vn/du-lieu/msn-1281895/msn120008-ngay-24122021-giao-dich-dau-tien-50000000-trai-phieu-niem-yet.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1281895/msn120008-ngay-24122021-giao-dich-dau-tien-50000000-trai-phieu-niem-yet.chn

📰 Crawl bài 642/1050: https://cafef.vn/du-lieu/msn-1284271/msn120009-ngay-24122021-giao-dich-dau-tien-5000000-trai-phieu-niem-yet.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1284271/msn120009-ngay-24122021-giao-dich-dau-tien-5000000-trai-phieu-niem-yet.chn

📰 Crawl bài 643/1050: https://cafef.vn/du-lieu/msn-1289701/msn120010-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1289701/msn120010-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn

📰 Crawl bài 644/1050: https://cafef.vn/du-lieu/msn-1289542/msn120010-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1289542/msn120010-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn

📰 Crawl bài 645/1050: https://cafef.vn/du-lieu/msn-1292005/msn120009-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1292005/msn120009-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn

📰 Crawl bài 646/1050: https://cafef.vn/du-lieu/msn-1286680/msn120009-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1286680/msn120009-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn

📰 Crawl bài 647/1050: https://cafef.vn/du-lieu/msn-1286740/msn120008-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1286740/msn120008-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn

📰 Crawl bài 648/1050: https://cafef.vn/du-lieu/msn-1286887/msn120008-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1286887/msn120008-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn

📰 Crawl bài 649/1050: https://cafef.vn/du-lieu/msn-1287451/msn120007-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1287451/msn120007-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn

📰 Crawl bài 650/1050: https://cafef.vn/du-lieu/msn-1288135/msn120007-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1288135/msn120007-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn

📰 Crawl bài 651/1050: https://cafef.vn/du-lieu/msn-1285993/msn121013-nghi-quyet-hdqt-ve-ngay-dkcc-va-xac-nhan-danh-sach-nguoi-so-huu-chung-khoan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1285993/msn121013-nghi-quyet-hdqt-ve-ngay-dkcc-va-xac-nhan-danh-sach-nguoi-so-huu-chung-khoan.chn

📰 Crawl bài 652/1050: https://cafef.vn/du-lieu/msn-1286698/msn121015-thong-bao-ngay-dang-ky-cuoi-cung-va-xac-nhan-danh-sach-nguoi-so-huu-chung-khoan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1286698/msn121015-thong-bao-ngay-dang-ky-cuoi-cung-va-xac-nhan-danh-sach-nguoi-so-huu-chung-khoan.chn

📰 Crawl bài 653/1050: https://cafef.vn/du-lieu/msn-1286836/msn121014-thong-bao-ngay-dang-ky-cuoi-cung-va-xac-nhan-danh-sach-nguoi-so-huu-chung-khoan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1286836/msn121014-thong-bao-ngay-dang-ky-cuoi-cung-va-xac-nhan-danh-sach-nguoi-so-huu-chung-khoan.chn

📰 Crawl bài 654/1050: https://cafef.vn/du-lieu/msn-1299082/msn-thong-cao-bao-chi-the-crownx-hop-tac-voi-tpg-adia-va-seatown-cong-bo-vong-huy-dong-von-dau-tu-tri-gia-350-trieu-usd.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1299082/msn-thong-cao-bao-chi-the-crownx-hop-tac-voi-tpg-adia-va-seatown-cong-bo-vong-huy-dong-von-dau-tu-tri-gia-350-trieu-usd.chn

📰 Crawl bài 655/1050: https://cafef.vn/du-lieu/msn-1291420/msn121013-tb-ngay-dang-ky-cuoi-cung-de-thuc-hien-quyen-chi-tra-trai-tuc-ky-nam-2022.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1291420/msn121013-tb-ngay-dang-ky-cuoi-cung-de-thuc-hien-quyen-chi-tra-trai-tuc-ky-nam-2022.chn

📰 Crawl bài 656/1050: https://cafef.vn/du-lieu/msn-1291573/msn120012-tb-lai-suat-cho-ky-tinh-lai-03-cua-tp-dao-han-nam-2023.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1291573/msn120012-tb-lai-suat-cho-ky-tinh-lai-03-cua-tp-dao-han-nam-2023.chn

📰 Crawl bài 657/1050: https://cafef.vn/du-lieu/msn-1292155/msn120011-tb-lai-suat-cho-ky-tinh-lai-03-cua-tp-dao-han-nam-2023.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1292155/msn120011-tb-lai-suat-cho-ky-tinh-lai-03-cua-tp-dao-han-nam-2023.chn

📰 Crawl bài 658/1050: https://cafef.vn/du-lieu/msn-1291498/msn121014-tb-ngay-dang-ky-cuoi-cung-de-thuc-hien-quyen-chi-tra-trai-tuc-ky-nam-2022.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1291498/msn121014-tb-ngay-dang-ky-cuoi-cung-de-thuc-hien-quyen-chi-tra-trai-tuc-ky-nam-2022.chn

📰 Crawl bài 659/1050: https://cafef.vn/du-lieu/msn-1291903/msn121015-tb-ngay-dang-ky-cuoi-cung-de-thuc-hien-quyen-chi-tra-trai-tuc-ky-nam-2022.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1291903/msn121015-tb-ngay-dang-ky-cuoi-cung-de-thuc-hien-quyen-chi-tra-trai-tuc-ky-nam-2022.chn

📰 Crawl bài 661/1050: https://cafef.vn/du-lieu/msn-1301533/msn-niem-yet-trai-phieu-tren-hnx.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1301533/msn-niem-yet-trai-phieu-tren-hnx.chn

📰 Crawl bài 662/1050: https://cafef.vn/du-lieu/msn-1298782/msn-ngay-dkcc-tra-trai-tuc-ky-2-cua-trai-phieu-msn121013-msn121014-msn121015.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1298782/msn-ngay-dkcc-tra-trai-tuc-ky-2-cua-trai-phieu-msn121013-msn121014-msn121015.chn

📰 Crawl bài 663/1050: https://cafef.vn/du-lieu/msn-1298704/msn-lai-suat-cho-ky-tinh-lai-03-cua-trai-phieu-msn120011-va-msn120012.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1298704/msn-lai-suat-cho-ky-tinh-lai-03-cua-trai-phieu-msn120011-va-msn120012.chn

📰 Crawl bài 665/1050: https://cafef.vn/du-lieu/msn-1306729/msn120011-ngay-14122021-giao-dich-dau-tien-5000000-trai-phieu-niem-yet.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1306729/msn120011-ngay-14122021-giao-dich-dau-tien-5000000-trai-phieu-niem-yet.chn

📰 Crawl bài 666/1050: https://cafef.vn/du-lieu/msn-1307044/msn121014-ngay-14122021-giao-dich-dau-tien-5000000-trai-phieu-niem-yet.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1307044/msn121014-ngay-14122021-giao-dich-dau-tien-5000000-trai-phieu-niem-yet.chn

📰 Crawl bài 667/1050: https://cafef.vn/du-lieu/msn-1307659/msn121015-ngay-14122021-giao-dich-dau-tien-4000000-trai-phieu-niem-yet.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1307659/msn121015-ngay-14122021-giao-dich-dau-tien-4000000-trai-phieu-niem-yet.chn

📰 Crawl bài 668/1050: https://cafef.vn/du-lieu/msn-1308046/msn120012-ngay-14122021-giao-dich-dau-tien-5000000-trai-phieu-niem-yet.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1308046/msn120012-ngay-14122021-giao-dich-dau-tien-5000000-trai-phieu-niem-yet.chn

📰 Crawl bài 669/1050: https://cafef.vn/du-lieu/msn-1308745/msn121013-ngay-14122021-giao-dich-dau-tien-5000000-trai-phieu-niem-yet.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1308745/msn121013-ngay-14122021-giao-dich-dau-tien-5000000-trai-phieu-niem-yet.chn

📰 Crawl bài 670/1050: https://cafef.vn/du-lieu/msn-1308574/msn-15122021-ngay-gdkhq-lay-y-kien-co-dong-bang-van-ban-tam-ung-co-tuc-dot-22021-250-dcp.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1308574/msn-15122021-ngay-gdkhq-lay-y-kien-co-dong-bang-van-ban-tam-ung-co-tuc-dot-22021-250-dcp.chn

📰 Crawl bài 671/1050: https://cafef.vn/du-lieu/msn-1309306/msn121015-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1309306/msn121015-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn

📰 Crawl bài 672/1050: https://cafef.vn/du-lieu/msn-1311547/msn121014-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1311547/msn121014-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn

📰 Crawl bài 673/1050: https://cafef.vn/du-lieu/msn-1312060/msn121015-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1312060/msn121015-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn

📰 Crawl bài 674/1050: https://cafef.vn/du-lieu/msn-1312171/msn121014-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1312171/msn121014-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn

📰 Crawl bài 675/1050: https://cafef.vn/du-lieu/msn-1308010/msn121013-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1308010/msn121013-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn

📰 Crawl bài 676/1050: https://cafef.vn/du-lieu/msn-1308865/msn121013-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1308865/msn121013-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn

📰 Crawl bài 677/1050: https://cafef.vn/du-lieu/msn-1310527/msn120012-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1310527/msn120012-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn

📰 Crawl bài 678/1050: https://cafef.vn/du-lieu/msn-1311250/msn120012-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1311250/msn120012-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn

📰 Crawl bài 679/1050: https://cafef.vn/du-lieu/msn-1311406/msn120011-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1311406/msn120011-ban-cong-bo-thong-tin-cua-ctcp-tap-doan-masan.chn

📰 Crawl bài 680/1050: https://cafef.vn/du-lieu/msn-1312294/msn120011-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1312294/msn120011-quyet-dinh-chap-thuan-niem-yet-trai-phieu-ctcp-tap-doan-masan.chn

📰 Crawl bài 682/1050: https://cafef.vn/du-lieu/msn-1329805/msn-tcbc-masan-tang-co-tuc-tien-mat-nam-2021-va-co-ke-hoach-phat-hanh-co-phieu-thuong.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1329805/msn-tcbc-masan-tang-co-tuc-tien-mat-nam-2021-va-co-ke-hoach-phat-hanh-co-phieu-thuong.chn

📰 Crawl bài 683/1050: https://cafef.vn/du-lieu/msn-1331815/msn-ngay-dkcc-lay-y-kien-co-dong-bang-van-ban-va-tam-ung-co-tuc-dot-2-nam-2021-bang-tien.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1331815/msn-ngay-dkcc-lay-y-kien-co-dong-bang-van-ban-va-tam-ung-co-tuc-dot-2-nam-2021-bang-tien.chn

📰 Crawl bài 687/1050: https://cafef.vn/du-lieu/msn-1338892/msn-thong-bao-lai-suat-cho-ky-tinh-lai-04.chn
⚠️ Không lấy được nội dung: https://cafef.vn/du-lieu/msn-1338892/msn-thong-bao-lai-suat-cho-ky-tinh-lai-04.chn

📰 Crawl bài 688/1050: https://cafef.vn/du-lieu/msn-1351048/msn120007-nhan-ho-so-dang-ky-niem-yet-chung-khoan-cua-cong-ty-co-phan-tap-doan-masan.chn

Phân tích cảm xúc bài báo

In [ ]:
# Cài đặt nếu chưa có
!pip install pandas torch transformers sentencepiece

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.8.0+cu126)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.56.1)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.14.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.35.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.10)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.8.3)

In [ ]:
pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.35.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)

In [ ]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, AutoConfig
import numpy as np
import torch

#### Load model
model_path = '5CD-AI/Vietnamese-Sentiment-visobert'
tokenizer = AutoTokenizer.from_pretrained(model_path)
config = AutoConfig.from_pretrained(model_path)
model = AutoModelForSequenceClassification.from_pretrained(model_path)

# Đảm bảo model ở chế độ CPU
device = torch.device("cpu")
model.to(device)

sentence = 'Cũng giống mấy khoá Youtube học cũng được'
print('Sentence:', sentence)

# Tokenize input
input_ids = torch.tensor([tokenizer.encode(sentence, add_special_tokens=True)]).to(device)

# Dự đoán
with torch.no_grad():
    out = model(input_ids)
    scores = out.logits.softmax(dim=-1).cpu().numpy()[0]

# In kết quả
ranking = np.argsort(scores)[::-1]
print("### Sentiment score ####")
for i in range(scores.shape[0]):
    label = config.id2label[ranking[i]]
    score = scores[ranking[i]]
    print(f"{i+1}) {label}: {np.round(float(score), 4)}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json: 0.00B [00:00, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/471k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/958 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/390M [00:00<?, ?B/s]

Sentence: Cũng giống mấy khoá Youtube học cũng được
### Sentiment score ####
1) NEU: 0.8928
2) NEG: 0.0586
3) POS: 0.0486

In [ ]:
import pandas as pd
import numpy as np
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer, AutoConfig
from tqdm import tqdm

# --- Cấu hình --- #
model_path = '5CD-AI/Vietnamese-Sentiment-visobert'
in_csv = '/content/drive/MyDrive/cafef_news/Cafef_news_100/msn_tech_news.csv'
out_csv = '/content/drive/MyDrive/cafef_news/Cafef_news_100/msn_tech_news.csv'    # <- file kết quả sẽ lưu ở đây
text_column = 'Nội dung'             # tên cột chứa toàn bộ paper (giữ nguyên dấu)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
aggregation_method = 'weighted'      # 'weighted' hoặc 'majority'

# --- Load model/tokenizer --- #
tokenizer = AutoTokenizer.from_pretrained(model_path)
config = AutoConfig.from_pretrained(model_path)
model = AutoModelForSequenceClassification.from_pretrained(model_path).to(device)
model.eval()

# --- Xác định kích thước chunk an toàn --- #
model_max_len = getattr(tokenizer, "model_max_length", None)
# bảo đảm model_max_len hợp lệ
if not model_max_len or model_max_len <= 0 or model_max_len > 1e6:
    model_max_len = 512
chunk_size = max(1, int(model_max_len) - 2)  # chừa 2 token cho special tokens

print(f"Device: {device}, tokenizer.model_max_length = {model_max_len}, chunk_size = {chunk_size}")

# --- Build mapping label -> index (tự động dò) --- #
label_map = {}
for k, v in config.id2label.items():
    idx = int(k)
    lab = str(v).lower()
    if 'pos' in lab:
        label_map['positive'] = idx
    elif 'neg' in lab:
        label_map['negative'] = idx
    elif 'neu' in lab or 'nat' in lab:  # 'neutral' hoặc biến thể
        label_map['neutral'] = idx

# Fallback nếu không dò được đủ nhãn
if not all(k in label_map for k in ('positive','neutral','negative')):
    ids = sorted([int(k) for k in config.id2label.keys()])
    if len(ids) == 3:
        # hay dùng cấu trúc phổ biến: 0=neg,1=neu,2=pos
        label_map = {'negative': ids[0], 'neutral': ids[1], 'positive': ids[2]}
    else:
        # nếu không rõ, gán tuần tự (người dùng nên kiểm tra lại)
        label_map = {}
        for i, idv in enumerate(ids):
            label_map[f'label_{i}'] = idv
print("Label map (resolved):", label_map)

# --- Hàm predict cho một văn bản (paper) --- #
def predict_probs_for_text(text, aggregation='weighted'):
    """
    Trả về vector probabilities (shape = num_labels) tương ứng chỉ số theo config.id2label.
    Aggregation: 'weighted' (mặc định) hoặc 'majority'
    """
    if not isinstance(text, str) or text.strip() == "":
        return None

    # Chia token (không thêm special tokens) rồi chunk
    token_ids = tokenizer.encode(text, add_special_tokens=False)
    if len(token_ids) == 0:
        return None

    chunks = [token_ids[i:i+chunk_size] for i in range(0, len(token_ids), chunk_size)]
    chunk_preds = []
    chunk_weights = []

    for ch in chunks:
        # decode token ids -> text cho chunk (sẽ được tokenizer lại với special tokens)
        ch_text = tokenizer.decode(ch, clean_up_tokenization_spaces=True)
        enc = tokenizer(ch_text,
                        truncation=True,
                        max_length=model_max_len,
                        return_tensors='pt',
                        padding=False)
        enc = {k: v.to(device) for k, v in enc.items()}

        with torch.no_grad():
            out = model(**enc)
            probs = torch.softmax(out.logits, dim=-1).cpu().numpy()[0]  # shape (num_labels,)
        chunk_preds.append(probs)
        chunk_weights.append(len(ch))  # trọng số = số token gốc trong chunk

    chunk_preds = np.stack(chunk_preds, axis=0)  # (n_chunks, n_labels)
    chunk_weights = np.array(chunk_weights, dtype=float)

    if aggregation == 'majority':
        # mỗi chunk lấy argmax -> vote
        votes = np.argmax(chunk_preds, axis=1)
        # convert votes to probability-like counts over label index order
        n_labels = chunk_preds.shape[1]
        counts = np.zeros(n_labels, dtype=float)
        for v in votes:
            counts[int(v)] += 1.0
        return counts / counts.sum()
    else:
        # weighted average theo số token (thường tốt hơn)
        weighted = np.average(chunk_preds, axis=0, weights=chunk_weights)
        return weighted

# --- Đọc CSV và chạy --- #
df = pd.read_csv(in_csv, encoding='utf-8-sig')

# Tạo/chuẩn hoá cột kết quả
for c in ['positive', 'neutral', 'negative']:
    if c not in df.columns:
        df[c] = np.nan

# Duyệt từng dòng
for idx, row in tqdm(df.iterrows(), total=len(df), desc="Processing rows"):
    try:
        text = row.get(text_column)
        if pd.isna(text) or str(text).strip() == "":
            continue
        probs = predict_probs_for_text(str(text), aggregation=aggregation_method)
        if probs is None:
            continue

        # Gán vào cột tương ứng dựa trên label_map
        if 'positive' in label_map:
            df.at[idx, 'positive'] = float(probs[int(label_map['positive'])])
        if 'neutral' in label_map:
            df.at[idx, 'neutral'] = float(probs[int(label_map['neutral'])])
        if 'negative' in label_map:
            df.at[idx, 'negative'] = float(probs[int(label_map['negative'])])
    except Exception as e:
        print(f"Error processing row {idx}: {e}")
        # continue để xử lý các dòng còn lại

# Lưu kết quả
df.to_csv(out_csv, index=False, encoding='utf-8-sig')
print("Đã lưu kết quả vào", out_csv)

Device: cpu, tokenizer.model_max_length = 256, chunk_size = 254
Label map (resolved): {'negative': 0, 'positive': 1, 'neutral': 2}

Processing rows:   0%|          | 0/60 [00:00<?, ?it/s]Token indices sequence length is longer than the specified maximum sequence length for this model (964 > 256). Running this sequence through the model will result in indexing errors
Processing rows: 100%|██████████| 60/60 [00:19<00:00,  3.03it/s]

Đã lưu kết quả vào /content/drive/MyDrive/cafef_news/Cafef_news_100/msn_tech_news.csv

In [ ]:
import pandas as pd
import numpy as np
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer, AutoConfig
from tqdm import tqdm

# --- Cấu hình --- #
model_path = '5CD-AI/Vietnamese-Sentiment-visobert'
in_csv = '/content/drive/MyDrive/cafef_news/cafef_vcb.csv'
out_csv = '/content/drive/MyDrive/cafef_news/Cafef_news_100/ket_qua_sentiment_vcb.csv'
text_column = 'Nội dung'             # tên cột chứa toàn bộ paper (giữ nguyên dấu)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
aggregation_method = 'weighted'      # 'weighted' hoặc 'majority'

# --- Load model/tokenizer --- #
tokenizer = AutoTokenizer.from_pretrained(model_path)
config = AutoConfig.from_pretrained(model_path)
model = AutoModelForSequenceClassification.from_pretrained(model_path).to(device)
model.eval()

# --- Xác định kích thước chunk an toàn --- #
model_max_len = getattr(tokenizer, "model_max_length", None)
# bảo đảm model_max_len hợp lệ
if not model_max_len or model_max_len <= 0 or model_max_len > 1e6:
    model_max_len = 512
chunk_size = max(1, int(model_max_len) - 2)  # chừa 2 token cho special tokens

print(f"Device: {device}, tokenizer.model_max_length = {model_max_len}, chunk_size = {chunk_size}")

# --- Build mapping label -> index (tự động dò) --- #
label_map = {}
for k, v in config.id2label.items():
    idx = int(k)
    lab = str(v).lower()
    if 'pos' in lab:
        label_map['positive'] = idx
    elif 'neg' in lab:
        label_map['negative'] = idx
    elif 'neu' in lab or 'nat' in lab:  # 'neutral' hoặc biến thể
        label_map['neutral'] = idx

# Fallback nếu không dò được đủ nhãn
if not all(k in label_map for k in ('positive','neutral','negative')):
    ids = sorted([int(k) for k in config.id2label.keys()])
    if len(ids) == 3:
        # hay dùng cấu trúc phổ biến: 0=neg,1=neu,2=pos
        label_map = {'negative': ids[0], 'neutral': ids[1], 'positive': ids[2]}
    else:
        # nếu không rõ, gán tuần tự (người dùng nên kiểm tra lại)
        label_map = {}
        for i, idv in enumerate(ids):
            label_map[f'label_{i}'] = idv
print("Label map (resolved):", label_map)

# --- Hàm predict cho một văn bản (paper) --- #
def predict_probs_for_text(text, aggregation='weighted'):
    """
    Trả về vector probabilities (shape = num_labels) tương ứng chỉ số theo config.id2label.
    Aggregation: 'weighted' (mặc định) hoặc 'majority'
    """
    if not isinstance(text, str) or text.strip() == "":
        return None

    # Chia token (không thêm special tokens) rồi chunk
    token_ids = tokenizer.encode(text, add_special_tokens=False)
    if len(token_ids) == 0:
        return None

    chunks = [token_ids[i:i+chunk_size] for i in range(0, len(token_ids), chunk_size)]
    chunk_preds = []
    chunk_weights = []

    for ch in chunks:
        # decode token ids -> text cho chunk (sẽ được tokenizer lại với special tokens)
        ch_text = tokenizer.decode(ch, clean_up_tokenization_spaces=True)
        enc = tokenizer(ch_text,
                        truncation=True,
                        max_length=model_max_len,
                        return_tensors='pt',
                        padding=False)
        enc = {k: v.to(device) for k, v in enc.items()}

        with torch.no_grad():
            out = model(**enc)
            probs = torch.softmax(out.logits, dim=-1).cpu().numpy()[0]  # shape (num_labels,)
        chunk_preds.append(probs)
        chunk_weights.append(len(ch))  # trọng số = số token gốc trong chunk

    chunk_preds = np.stack(chunk_preds, axis=0)  # (n_chunks, n_labels)
    chunk_weights = np.array(chunk_weights, dtype=float)

    if aggregation == 'majority':
        # mỗi chunk lấy argmax -> vote
        votes = np.argmax(chunk_preds, axis=1)
        # convert votes to probability-like counts over label index order
        n_labels = chunk_preds.shape[1]
        counts = np.zeros(n_labels, dtype=float)
        for v in votes:
            counts[int(v)] += 1.0
        return counts / counts.sum()
    else:
        # weighted average theo số token (thường tốt hơn)
        weighted = np.average(chunk_preds, axis=0, weights=chunk_weights)
        return weighted

# --- Đọc CSV và chạy --- #
df = pd.read_csv(in_csv, encoding='utf-8-sig')

# Tạo/chuẩn hoá cột kết quả
for c in ['positive', 'neutral', 'negative']:
    if c not in df.columns:
        df[c] = np.nan

# Duyệt từng dòng
for idx, row in tqdm(df.iterrows(), total=len(df), desc="Processing rows"):
    try:
        text = row.get(text_column)
        if pd.isna(text) or str(text).strip() == "":
            continue
        probs = predict_probs_for_text(str(text), aggregation=aggregation_method)
        if probs is None:
            continue

        # Gán vào cột tương ứng dựa trên label_map
        if 'positive' in label_map:
            df.at[idx, 'positive'] = float(probs[int(label_map['positive'])])
        if 'neutral' in label_map:
            df.at[idx, 'neutral'] = float(probs[int(label_map['neutral'])])
        if 'negative' in label_map:
            df.at[idx, 'negative'] = float(probs[int(label_map['negative'])])
    except Exception as e:
        print(f"Error processing row {idx}: {e}")
        # continue để xử lý các dòng còn lại

# Lưu kết quả
df.to_csv(out_csv, index=False, encoding='utf-8-sig')
print("Đã lưu kết quả vào", out_csv)

Device: cuda, tokenizer.model_max_length = 256, chunk_size = 254
Label map (resolved): {'negative': 0, 'positive': 1, 'neutral': 2}

Processing rows:   0%|          | 0/750 [00:00<?, ?it/s]Token indices sequence length is longer than the specified maximum sequence length for this model (792 > 256). Running this sequence through the model will result in indexing errors
Processing rows: 100%|██████████| 750/750 [00:00<00:00, 1039.80it/s]

Đã lưu kết quả vào /content/drive/MyDrive/cafef_news/Cafef_news_100/ket_qua_sentiment_vcb.csv

In [ ]:
df

,Thời gian,Tiêu đề,URL,Nội dung,positive,neutral,negative
0,2025-09-23 08:13:00,Ông Donald Trump tuyên bố áp 100.000 USD cho v...,https://cafef.vn/ong-donald-trump-tuyen-bo-ap-...,"Theo FPT, hiện tại công ty có vài chục nhân vi...",0.378505,0.576057,0.045438
1,2025-09-18 11:22:00,FPT hoàn thành tăng vốn điều lệ lên hơn 17 ngh...,https://cafef.vn/fpt-hoan-thanh-tang-von-dieu-...,"Nguồn vốn ngân sách nhà nước đang nắm giữ 5,7%...",0.737829,0.260381,0.001789
2,2025-09-16 17:30:00,Tập đoàn công nghệ hàng đầu Việt Nam vừa có bả...,https://cafef.vn/tap-doan-cong-nghe-hang-dau-v...,"Trước đó, doanh nghiệp này cũng đã ký nhiều hợ...",0.989165,0.010211,0.000624
3,2025-09-16 13:49:00,FPT ký kết hợp tác AI mở ra cơ hội lên đến 30 ...,https://cafef.vn/fpt-ky-ket-hop-tac-ai-mo-ra-c...,Hợp tác này đánh dấu cột mốc quan trọng trong ...,0.984766,0.014987,0.000248
4,2025-09-16 08:00:00,FPT ký hợp đồng kỷ lục 256 triệu USD với tập đ...,https://cafef.vn/fpt-ky-hop-dong-ky-luc-256-tr...,Các hợp đồng quy mô trăm triệu USD không chỉ m...,0.998152,0.001634,0.000214
...,...,...,...,...,...,...,...
295,2024-01-22 08:26:00,"FPT City bán hết 699 căn hộ chỉ trong 6 tháng,...",https://cafef.vn/du-lieu/fpt-1934022/fpt-city-...,NaN,NaN,NaN,NaN
296,2024-01-19 07:27:00,FPT: Lợi nhuận trước thuế 2023 tăng hơn 20% lê...,https://cafef.vn/du-lieu/fpt-1932838/fpt-loi-n...,NaN,NaN,NaN,NaN
297,2024-01-19 00:00:00,FPT: Công bố kết quả kinh doanh năm 2023,https://cafef.vn/du-lieu/fpt-1933855/fpt-cong-...,NaN,NaN,NaN,NaN
298,2024-01-17 10:12:00,"Ông Trương Gia Bình: Thanh niên Mỹ, Nhật Bản, ...",https://cafef.vn/du-lieu/fpt-1931462/ong-truon...,NaN,NaN,NaN,NaN
299,2024-01-14 07:41:00,"VinFast, GSM cùng hai doanh nghiệp niêm yết tỷ...",https://cafef.vn/du-lieu/fpt-1929908/vinfast-g...,NaN,NaN,NaN,NaN

In [ ]:
pip install underthesea

Collecting underthesea
  Downloading underthesea-8.3.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.12/dist-packages (from underthesea) (8.2.1)
Collecting python-crfsuite>=0.9.6 (from underthesea)
  Downloading python_crfsuite-0.9.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.3 kB)
Requirement already satisfied: nltk>=3.8 in /usr/local/lib/python3.12/dist-packages (from underthesea) (3.9.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from underthesea) (4.67.1)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from underthesea) (2.32.4)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from underthesea) (1.5.2)
Requirement already satisfied: scikit-learn>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from underthesea) (1.6.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from underthesea) (6.0.2)
Collecting underthesea_core==1.0.5 (from underthesea)
  Downloading underthesea_core-1.0.5-cp312-cp312-manylinux2010_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.12/dist-packages (from underthesea) (0.35.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.8->underthesea) (2024.11.6)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.1->underthesea) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.1->underthesea) (1.16.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.1->underthesea) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->underthesea) (3.19.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->underthesea) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->underthesea) (25.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->underthesea) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->underthesea) (1.1.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->underthesea) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->underthesea) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->underthesea) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->underthesea) (2025.8.3)
Downloading underthesea-8.3.0-py3-none-any.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 70.0 MB/s eta 0:00:00
Downloading underthesea_core-1.0.5-cp312-cp312-manylinux2010_x86_64.whl (978 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 978.4/978.4 kB 38.4 MB/s eta 0:00:00
Downloading python_crfsuite-0.9.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 68.2 MB/s eta 0:00:00
Installing collected packages: underthesea_core, python-crfsuite, underthesea
Successfully installed python-crfsuite-0.9.11 underthesea-8.3.0 underthesea_core-1.0.5

In [ ]:
import os
import re
import time
import json
import ast
import random
import pandas as pd
import google.generativeai as genai
from collections import Counter

# ====== CẤU HÌNH ======
API_KEY = os.getenv("GENAI_API_KEY", "AIzaSyB_AQF4AqEPB6qypx3KOJFm8KzhLWi1Fc8")
genai.configure(api_key=API_KEY)

MODEL_NAME = "gemini-2.5-pro"
model = genai.GenerativeModel(MODEL_NAME)

# ====== THAM SỐ TÙY CHỈNH ======
CSV_PATH = '/content/drive/MyDrive/cafef_news/Cafef_news_100/ket_qua_sentiment_vcb.csv'
MAIN_COMPANY = "vietcombank"
START_NEWS = 0
END_NEWS = 50
MAX_CHUNK_LEN = 800

# Delay giữa các đoạn, bài và nhóm
CHUNK_DELAY = 1
ARTICLE_DELAY_MIN, ARTICLE_DELAY_MAX = 3, 6    # nghỉ 3–6s giữa các bài
GROUP_DELAY_MIN, GROUP_DELAY_MAX = 70, 90      # nghỉ 70–90s giữa các nhóm
API_RETRIES = 2
RETRY_DELAY = 4

GROUP_SIZE = 10  # mỗi nhóm 10 bài

# ====== HÀM HỖ TRỢ ======
def split_text(text, max_len=MAX_CHUNK_LEN):
    text = str(text).strip()
    if not text:
        return []
    chunks = []
    while len(text) > max_len:
        cut = text[:max_len]
        last_dot = cut.rfind(".")
        if last_dot == -1:
            last_dot = max_len
        chunks.append(text[:last_dot+1].strip())
        text = text[last_dot+1:].strip()
    if text:
        chunks.append(text)
    return chunks


def parse_model_list_output(text_out):
    text_out = (text_out or "").strip()
    text_out = re.sub(r"^```[\w\W]*?\n", "", text_out)
    text_out = re.sub(r"\n```$", "", text_out)
    try:
        parsed = json.loads(text_out)
        if isinstance(parsed, list):
            return parsed
    except Exception:
        pass
    try:
        parsed = ast.literal_eval(text_out)
        if isinstance(parsed, list):
            return parsed
    except Exception:
        pass
    quotes = re.findall(r'"([^"]+)"|\'([^\']+)\'', text_out)
    if quotes:
        return [a if a else b for a, b in quotes]
    m = re.search(r"\[(.*)\]", text_out, re.DOTALL)
    if m:
        inner = m.group(1)
        tokens = [t.strip(" \"'") for t in inner.split(",") if t.strip()]
        return tokens
    return []


def normalize_org_list(orgs):
    clean = []
    for org in orgs:
        if not isinstance(org, str):
            continue
        s = re.sub(r'[^\w\s]', '', org).strip()
        if len(s) > 1:
            clean.append(s.lower())
    return clean


def call_model_with_retries(prompt, retries=API_RETRIES):
    last_err = None
    for attempt in range(1, retries+1):
        try:
            resp = model.generate_content(prompt)
            text_out = resp.text if hasattr(resp, "text") and resp.text else str(resp)
            return text_out
        except Exception as e:
            last_err = e
            print(f"  [WARN] Lỗi gọi model (lần {attempt}/{retries}): {e}")
            if attempt < retries:
                time.sleep(RETRY_DELAY)
    print(f"  [ERROR] Gọi model thất bại sau {retries} lần: {last_err}")
    return None


def extract_orgs_from_chunk(chunk):
    prompt = f"""
Hãy trích xuất tất cả tên tổ chức/công ty (ORGANIZATION) trong đoạn văn dưới đây.
Chỉ trả về kết quả là JSON list, ví dụ ["FPT", "Viettel", "VinGroup"].

Văn bản:
{chunk}
"""
    text_out = call_model_with_retries(prompt)
    if not text_out:
        return []
    orgs_raw = parse_model_list_output(text_out)
    return normalize_org_list(orgs_raw)


# ====== LOAD CSV ======
df = pd.read_csv(CSV_PATH)
if 'Nội dung' not in df.columns:
    raise SystemExit("Cột 'Nội dung' không tồn tại trong file CSV.")

articles_all = df['Nội dung'].dropna().reset_index(drop=True)
total_available = len(articles_all)
print(f"Tổng số bài có nội dung: {total_available}")

# ====== CHỌN PHẠM VI BÀI BÁO ======
start_idx = max(0, START_NEWS)
end_idx = min(END_NEWS, total_available)
if start_idx >= end_idx:
    raise SystemExit("Phạm vi START_NEWS..END_NEWS không hợp lệ hoặc không có bài để xử lý.")
articles = articles_all.iloc[start_idx:end_idx].reset_index(drop=True)
print(f"Xử lý các bài báo từ {start_idx+1} đến {end_idx} (tổng {len(articles)} bài).")

# ====== MAIN LOOP ======
all_entities = Counter()
i = 0
group_number = 0

while i < len(articles):
    group_entities = Counter()
    group_number += 1
    group_start = i
    group_end = min(i + GROUP_SIZE, len(articles))
    print(f"\n>>> Bắt đầu nhóm #{group_number}: bài {group_start+1} → {group_end}")

    for j in range(GROUP_SIZE):
        idx = i + j
        if idx >= len(articles):
            break

        print(f" Processing article {idx+1}/{len(articles)}", end=" ... ")
        article_text = articles.iloc[idx]
        chunks = split_text(article_text)
        if not chunks:
            print(" (no text)")
            continue

        article_orgs = set()
        for k, chunk in enumerate(chunks, start=1):
            orgs = extract_orgs_from_chunk(chunk)
            if orgs:
                article_orgs.update(orgs)
                print(f"[chunk {k}/{len(chunks)}: {len(orgs)} orgs]", end=" ")
            else:
                print(f"[chunk {k}/{len(chunks)}: 0]", end=" ")
            time.sleep(CHUNK_DELAY)

        if article_orgs:
            group_entities.update(article_orgs)
            all_entities.update(article_orgs)
            print(f"=> {len(article_orgs)} orgs.")
        else:
            print("=> none.")

        # nghỉ ngẫu nhiên giữa các bài
        delay = random.uniform(ARTICLE_DELAY_MIN, ARTICLE_DELAY_MAX)
        print(f"  (nghỉ {delay:.1f}s) ...")
        time.sleep(delay)

    # In top group
    print(f"\n--- Nhóm #{group_number} ({group_start+1}-{group_end}) ---")
    filtered_group = Counter({c: cnt for c, cnt in group_entities.items() if c != MAIN_COMPANY.lower()})
    if filtered_group:
        for rank, (comp, cnt) in enumerate(filtered_group.most_common(10), start=1):
            print(f"{rank}. {comp}: {cnt}")
    else:
        print(" (Không có entity nào được trích xuất.)")

    # lưu tạm
    try:
        tmp_df = pd.DataFrame(all_entities.items(), columns=["org", "count"]).sort_values("count", ascending=False)
        tmp_df.to_csv(f"all_entities_until_{group_end}.csv", index=False, encoding="utf-8-sig")
    except Exception as e:
        print(f"[WARN] Không lưu được all_entities tạm: {e}")

    # nghỉ ngẫu nhiên giữa các nhóm
    i += GROUP_SIZE
    if i < len(articles):
        group_sleep = random.uniform(GROUP_DELAY_MIN, GROUP_DELAY_MAX)
        print(f"\n--- Nghỉ {group_sleep:.1f} giây trước nhóm tiếp theo ---\n")
        time.sleep(group_sleep)

# ====== KẾT QUẢ TOÀN BỘ ======
filtered_entities = Counter({comp: cnt for comp, cnt in all_entities.items() if comp != MAIN_COMPANY.lower()})
print(f"\n=== TỔNG HỢP TOÀN BỘ (loại bỏ '{MAIN_COMPANY}') ===")
if filtered_entities:
    for comp, cnt in filtered_entities.most_common(20):
        print(f"{comp}: {cnt}")
else:
    print(" (Không có entity nào được trích xuất.)")

Tổng số bài có nội dung: 183
Xử lý các bài báo từ 1 đến 50 (tổng 50 bài).

>>> Bắt đầu nhóm #1: bài 1 → 10
 Processing article 1/50 ...   [WARN] Lỗi gọi model (lần 1/2): HTTPConnectionPool(host='localhost', port=40811): Read timed out. (read timeout=600.0)

In [ ]:
import pandas as pd
import os
from datetime import datetime

# Danh sách các mã công ty
companies = ['FPT', 'HPG', 'GAS', 'SSI', 'VCB']

# Thư mục chứa file CSV
folder_path = '/content/'

# Dictionary để lưu kết quả
results = {}

for code in companies:
    file_path = os.path.join(folder_path, f'{code}_sentiment.csv')

    if os.path.exists(file_path):
        # Đọc file CSV
        df = pd.read_csv(file_path)

        # Tính tổng số bài báo từ cột 'số_bài_báo'
        total_articles = df['số_bài_báo'].sum()

        # Xử lý cột 'Thời gian' (giả sử là cột datetime, nếu không phải thì cần convert)
        df['Thời gian'] = pd.to_datetime(df['Thời gian'], errors='coerce')  # Convert sang datetime nếu chưa
        min_date = df['Thời gian'].min().strftime('%Y-%m-%d') if not pd.isna(df['Thời gian'].min()) else 'N/A'
        max_date = df['Thời gian'].max().strftime('%Y-%m-%d') if not pd.isna(df['Thời gian'].max()) else 'N/A'

        # Lưu kết quả
        results[code] = {
            'Tổng bài báo': total_articles,
            'Từ ngày': min_date,
            'Đến ngày': max_date
        }
    else:
        results[code] = {
            'Tổng bài báo': 'File không tồn tại',
            'Từ ngày': 'N/A',
            'Đến ngày': 'N/A'
        }

# In kết quả dưới dạng bảng
print("Kết quả thống kê:")
for code, data in results.items():
    print(f"\n{code}:")
    print(f"  Tổng bài báo: {data['Tổng bài báo']}")
    print(f"  Thời gian: {data['Từ ngày']} đến {data['Đến ngày']}")

Kết quả thống kê:

FPT:
  Tổng bài báo: 111
  Thời gian: 2025-01-01 đến 2025-10-07

HPG:
  Tổng bài báo: 178
  Thời gian: 2024-02-01 đến 2025-10-14

GAS:
  Tổng bài báo: 146
  Thời gian: 2020-01-20 đến 2025-11-09

SSI:
  Tổng bài báo: 117
  Thời gian: 2020-01-20 đến 2025-09-12

VCB:
  Tổng bài báo: 297
  Thời gian: 2020-01-10 đến 2025-09-23

In [ ]:
import pandas as pd
import time
import os
from datetime import datetime
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException

# --- Khởi tạo Edge driver ---
def init_driver():
    options = webdriver.EdgeOptions()
    options.add_argument("--headless")
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    driver = webdriver.Edge(options=options)
    return driver


# --- Hàm crawl nội dung 1 bài báo ---
def crawl_article_content(url):
    driver = init_driver()
    try:
        driver.get(url)
        time.sleep(2)  # chờ load JS

        content_texts = []

        # Tìm phần detail-content
        try:
            detail = driver.find_element(
                By.XPATH, '//div[contains(@class, "detail-content")]'
            )
        except NoSuchElementException:
            detail = None

        if detail:
            # Lấy sapo nếu có
            try:
                sapo = detail.find_element(By.XPATH, './/h2').text.strip()
                if sapo:
                    content_texts.append(sapo)
            except NoSuchElementException:
                pass

            # Lấy tất cả các đoạn <p>
            paras = detail.find_elements(By.XPATH, './/p')
            for p in paras:
                txt = p.text.strip()
                if txt and not txt.startswith(">>>"):  # bỏ dòng quảng cáo
                    content_texts.append(txt)

        # Nếu không tìm thấy detail-content thì fallback sang mainContent
        if not content_texts:
            try:
                paras2 = driver.find_elements(By.XPATH, '//*[@id="mainContent"]//p')
                for p in paras2:
                    txt = p.text.strip()
                    if txt:
                        content_texts.append(txt)
            except NoSuchElementException:
                pass

        return "\n".join(content_texts) if content_texts else None

    except Exception as e:
        print(f" Lỗi khi crawl {url}: {e}")
        return None
    finally:
        driver.quit()


# --- File CSV đầu vào ---
file_path = "/content/drive/MyDrive/cafef_news/ket_qua_sentiment_fpt.csv"

if not os.path.exists(file_path):
    print(f" Error: File not found at {file_path}")
else:
    df = pd.read_csv(file_path)

    # Nếu chưa có cột "Nội dung" thì thêm
    if "Nội dung" not in df.columns:
        df["Nội dung"] = None

    # Chuẩn hóa thời gian
    df["Thời gian"] = pd.to_datetime(
        df["Thời gian"], errors="coerce"
    )


    # Lọc khoảng thời gian
    start_date = datetime(2024, 1, 1)
    end_date = datetime(2025, 10, 15)
    mask = (df["Thời gian"] >= start_date) & (df["Thời gian"] <= end_date)
    df_target = df[mask]
    print(f" Có {len(df_target)} bài trong khoảng từ {start_date.date()} đến {end_date.date()}")

    # Crawl nội dung
    for i, row in df_target.iterrows():
        if pd.isna(row["Nội dung"]) or not row["Nội dung"]:
            url = row["URL"]
            print(f" Crawl {i+1}/{len(df_target)}: {url}")
            content = crawl_article_content(url)
            df.at[i, "Nội dung"] = content

            # Lưu tạm để tránh mất dữ liệu
            df.to_csv(file_path, index=False, encoding="utf-8-sig")

    print(f"\n Đã cập nhật nội dung vào file: {file_path}")

 Có 304 bài trong khoảng từ 2024-01-01 đến 2025-10-15
 Crawl 747/304: https://cafef.vn/du-lieu/fpt-1925779/fpt-ong-nguyen-viet-thang-truong-bks-dang-ky-ban-35000-cp.chn

KeyboardInterrupt